[package]
name = "centrode_domain"
version = "0.7.0"
edition = "2021"
description = "Pure domain models, types, and traits for Centrode."
authors = ["Celestios <shahin.id5638@gmail.com>"]

[dependencies]
centrode_macros.workspace = true
serde.workspace = true
surrealdb.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
flutter_rust_bridge.workspace = true
