// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'bridge/api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/base_models.dart';
import 'domain/config.dart';
import 'domain/nodes.dart';
import 'domain/relations.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'persistence/repo.dart';
import 'telemetry.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RepositoryPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    dynamic raw,
  );

  @protected
  Repository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    dynamic raw,
  );

  @protected
  AppHandle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    dynamic raw,
  );

  @protected
  AppHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    dynamic raw,
  );

  @protected
  Map<String, StyleProfile> dco_decode_Map_String_style_profile_None(
    dynamic raw,
  );

  @protected
  AppHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    dynamic raw,
  );

  @protected
  Repository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogState> dco_decode_StreamSink_log_state_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlockAttrs dco_decode_block_attrs(dynamic raw);

  @protected
  BlockType dco_decode_block_type(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BlockAttrs dco_decode_box_autoadd_block_attrs(dynamic raw);

  @protected
  Content dco_decode_box_autoadd_content(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  INode dco_decode_box_autoadd_i_node(dynamic raw);

  @protected
  InterNode dco_decode_box_autoadd_inter_node(dynamic raw);

  @protected
  MapConfig dco_decode_box_autoadd_map_config(dynamic raw);

  @protected
  MarkAttrs dco_decode_box_autoadd_mark_attrs(dynamic raw);

  @protected
  NodeInput dco_decode_box_autoadd_node_input(dynamic raw);

  @protected
  NodeOutput dco_decode_box_autoadd_node_output(dynamic raw);

  @protected
  RelationInput dco_decode_box_autoadd_relation_input(dynamic raw);

  @protected
  TaskNode dco_decode_box_autoadd_task_node(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  Comment dco_decode_comment(dynamic raw);

  @protected
  Content dco_decode_content(dynamic raw);

  @protected
  ContentBlock dco_decode_content_block(dynamic raw);

  @protected
  Coordinates dco_decode_coordinates(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  INode dco_decode_i_node(dynamic raw);

  @protected
  IRelation dco_decode_i_relation(dynamic raw);

  @protected
  InlineElement dco_decode_inline_element(dynamic raw);

  @protected
  InlineType dco_decode_inline_type(dynamic raw);

  @protected
  InterNode dco_decode_inter_node(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Comment> dco_decode_list_comment(dynamic raw);

  @protected
  List<ContentBlock> dco_decode_list_content_block(dynamic raw);

  @protected
  List<IRelation> dco_decode_list_i_relation(dynamic raw);

  @protected
  List<InlineElement> dco_decode_list_inline_element(dynamic raw);

  @protected
  List<NodeOutput> dco_decode_list_node_output(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, StyleProfile)> dco_decode_list_record_string_style_profile(
    dynamic raw,
  );

  @protected
  List<TextMark> dco_decode_list_text_mark(dynamic raw);

  @protected
  LogState dco_decode_log_state(dynamic raw);

  @protected
  MapConfig dco_decode_map_config(dynamic raw);

  @protected
  MarkAttrs dco_decode_mark_attrs(dynamic raw);

  @protected
  MarkType dco_decode_mark_type(dynamic raw);

  @protected
  NodeInput dco_decode_node_input(dynamic raw);

  @protected
  NodeOutput dco_decode_node_output(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BlockAttrs? dco_decode_opt_box_autoadd_block_attrs(dynamic raw);

  @protected
  Content? dco_decode_opt_box_autoadd_content(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MapConfig? dco_decode_opt_box_autoadd_map_config(dynamic raw);

  @protected
  MarkAttrs? dco_decode_opt_box_autoadd_mark_attrs(dynamic raw);

  @protected
  NodeOutput? dco_decode_opt_box_autoadd_node_output(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  List<TextMark>? dco_decode_opt_list_text_mark(dynamic raw);

  @protected
  (List<NodeOutput>, List<IRelation>, MapConfig?)
  dco_decode_record_list_node_output_list_i_relation_opt_box_autoadd_map_config(
    dynamic raw,
  );

  @protected
  (String, StyleProfile) dco_decode_record_string_style_profile(dynamic raw);

  @protected
  RelationInput dco_decode_relation_input(dynamic raw);

  @protected
  StyleProfile dco_decode_style_profile(dynamic raw);

  @protected
  TaskNode dco_decode_task_node(dynamic raw);

  @protected
  TextMark dco_decode_text_mark(dynamic raw);

  @protected
  ThemeConfig dco_decode_theme_config(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ViewportState dco_decode_viewport_state(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    SseDeserializer deserializer,
  );

  @protected
  Repository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    SseDeserializer deserializer,
  );

  @protected
  AppHandle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    SseDeserializer deserializer,
  );

  @protected
  AppHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, StyleProfile> sse_decode_Map_String_style_profile_None(
    SseDeserializer deserializer,
  );

  @protected
  AppHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    SseDeserializer deserializer,
  );

  @protected
  Repository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogState> sse_decode_StreamSink_log_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlockAttrs sse_decode_block_attrs(SseDeserializer deserializer);

  @protected
  BlockType sse_decode_block_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BlockAttrs sse_decode_box_autoadd_block_attrs(SseDeserializer deserializer);

  @protected
  Content sse_decode_box_autoadd_content(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  INode sse_decode_box_autoadd_i_node(SseDeserializer deserializer);

  @protected
  InterNode sse_decode_box_autoadd_inter_node(SseDeserializer deserializer);

  @protected
  MapConfig sse_decode_box_autoadd_map_config(SseDeserializer deserializer);

  @protected
  MarkAttrs sse_decode_box_autoadd_mark_attrs(SseDeserializer deserializer);

  @protected
  NodeInput sse_decode_box_autoadd_node_input(SseDeserializer deserializer);

  @protected
  NodeOutput sse_decode_box_autoadd_node_output(SseDeserializer deserializer);

  @protected
  RelationInput sse_decode_box_autoadd_relation_input(
    SseDeserializer deserializer,
  );

  @protected
  TaskNode sse_decode_box_autoadd_task_node(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Comment sse_decode_comment(SseDeserializer deserializer);

  @protected
  Content sse_decode_content(SseDeserializer deserializer);

  @protected
  ContentBlock sse_decode_content_block(SseDeserializer deserializer);

  @protected
  Coordinates sse_decode_coordinates(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  INode sse_decode_i_node(SseDeserializer deserializer);

  @protected
  IRelation sse_decode_i_relation(SseDeserializer deserializer);

  @protected
  InlineElement sse_decode_inline_element(SseDeserializer deserializer);

  @protected
  InlineType sse_decode_inline_type(SseDeserializer deserializer);

  @protected
  InterNode sse_decode_inter_node(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Comment> sse_decode_list_comment(SseDeserializer deserializer);

  @protected
  List<ContentBlock> sse_decode_list_content_block(
    SseDeserializer deserializer,
  );

  @protected
  List<IRelation> sse_decode_list_i_relation(SseDeserializer deserializer);

  @protected
  List<InlineElement> sse_decode_list_inline_element(
    SseDeserializer deserializer,
  );

  @protected
  List<NodeOutput> sse_decode_list_node_output(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, StyleProfile)> sse_decode_list_record_string_style_profile(
    SseDeserializer deserializer,
  );

  @protected
  List<TextMark> sse_decode_list_text_mark(SseDeserializer deserializer);

  @protected
  LogState sse_decode_log_state(SseDeserializer deserializer);

  @protected
  MapConfig sse_decode_map_config(SseDeserializer deserializer);

  @protected
  MarkAttrs sse_decode_mark_attrs(SseDeserializer deserializer);

  @protected
  MarkType sse_decode_mark_type(SseDeserializer deserializer);

  @protected
  NodeInput sse_decode_node_input(SseDeserializer deserializer);

  @protected
  NodeOutput sse_decode_node_output(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BlockAttrs? sse_decode_opt_box_autoadd_block_attrs(
    SseDeserializer deserializer,
  );

  @protected
  Content? sse_decode_opt_box_autoadd_content(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MapConfig? sse_decode_opt_box_autoadd_map_config(
    SseDeserializer deserializer,
  );

  @protected
  MarkAttrs? sse_decode_opt_box_autoadd_mark_attrs(
    SseDeserializer deserializer,
  );

  @protected
  NodeOutput? sse_decode_opt_box_autoadd_node_output(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  List<TextMark>? sse_decode_opt_list_text_mark(SseDeserializer deserializer);

  @protected
  (List<NodeOutput>, List<IRelation>, MapConfig?)
  sse_decode_record_list_node_output_list_i_relation_opt_box_autoadd_map_config(
    SseDeserializer deserializer,
  );

  @protected
  (String, StyleProfile) sse_decode_record_string_style_profile(
    SseDeserializer deserializer,
  );

  @protected
  RelationInput sse_decode_relation_input(SseDeserializer deserializer);

  @protected
  StyleProfile sse_decode_style_profile(SseDeserializer deserializer);

  @protected
  TaskNode sse_decode_task_node(SseDeserializer deserializer);

  @protected
  TextMark sse_decode_text_mark(SseDeserializer deserializer);

  @protected
  ThemeConfig sse_decode_theme_config(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ViewportState sse_decode_viewport_state(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    AppHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    Repository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    AppHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    AppHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_style_profile_None(
    Map<String, StyleProfile> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    AppHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    Repository self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_state_Sse(
    RustStreamSink<LogState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_block_attrs(BlockAttrs self, SseSerializer serializer);

  @protected
  void sse_encode_block_type(BlockType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_block_attrs(
    BlockAttrs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_node(INode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_inter_node(
    InterNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_map_config(
    MapConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mark_attrs(
    MarkAttrs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_input(
    NodeInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_output(
    NodeOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_relation_input(
    RelationInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_node(
    TaskNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_comment(Comment self, SseSerializer serializer);

  @protected
  void sse_encode_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_content_block(ContentBlock self, SseSerializer serializer);

  @protected
  void sse_encode_coordinates(Coordinates self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_i_node(INode self, SseSerializer serializer);

  @protected
  void sse_encode_i_relation(IRelation self, SseSerializer serializer);

  @protected
  void sse_encode_inline_element(InlineElement self, SseSerializer serializer);

  @protected
  void sse_encode_inline_type(InlineType self, SseSerializer serializer);

  @protected
  void sse_encode_inter_node(InterNode self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comment(List<Comment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_content_block(
    List<ContentBlock> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_i_relation(
    List<IRelation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_inline_element(
    List<InlineElement> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_node_output(
    List<NodeOutput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_style_profile(
    List<(String, StyleProfile)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_text_mark(List<TextMark> self, SseSerializer serializer);

  @protected
  void sse_encode_log_state(LogState self, SseSerializer serializer);

  @protected
  void sse_encode_map_config(MapConfig self, SseSerializer serializer);

  @protected
  void sse_encode_mark_attrs(MarkAttrs self, SseSerializer serializer);

  @protected
  void sse_encode_mark_type(MarkType self, SseSerializer serializer);

  @protected
  void sse_encode_node_input(NodeInput self, SseSerializer serializer);

  @protected
  void sse_encode_node_output(NodeOutput self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_block_attrs(
    BlockAttrs? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_content(
    Content? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_map_config(
    MapConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mark_attrs(
    MarkAttrs? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_node_output(
    NodeOutput? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_text_mark(
    List<TextMark>? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_record_list_node_output_list_i_relation_opt_box_autoadd_map_config(
    (List<NodeOutput>, List<IRelation>, MapConfig?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_style_profile(
    (String, StyleProfile) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relation_input(RelationInput self, SseSerializer serializer);

  @protected
  void sse_encode_style_profile(StyleProfile self, SseSerializer serializer);

  @protected
  void sse_encode_task_node(TaskNode self, SseSerializer serializer);

  @protected
  void sse_encode_text_mark(TextMark self, SseSerializer serializer);

  @protected
  void sse_encode_theme_config(ThemeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_viewport_state(ViewportState self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRepository(
    int ptr,
  );
}
