// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'config.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ComputedRelation {
  final String id;
  final List<Point> pathPoints;
  final PathType pathType;
  final Point startTangent;
  final Point endTangent;
  final Float64List bodyWidths;
  final BodyType bodyType;
  final EndpointShapeType startEndpoint;
  final EndpointShapeType endEndpoint;
  final double startDirection;
  final double endDirection;
  final Point labelPosition;
  final LabelAnchor labelAnchor;
  final String? bundleId;
  final double? bundleOffset;
  final List<Point> hitTestPoints;
  final List<String> dependsOnNodes;
  final Rect bbox;
  final double startMargin;
  final double endMargin;
  final Point startArrowCenter;
  final Point endArrowCenter;
  final Point startPoint;
  final Point endPoint;

  const ComputedRelation({
    required this.id,
    required this.pathPoints,
    required this.pathType,
    required this.startTangent,
    required this.endTangent,
    required this.bodyWidths,
    required this.bodyType,
    required this.startEndpoint,
    required this.endEndpoint,
    required this.startDirection,
    required this.endDirection,
    required this.labelPosition,
    required this.labelAnchor,
    this.bundleId,
    this.bundleOffset,
    required this.hitTestPoints,
    required this.dependsOnNodes,
    required this.bbox,
    required this.startMargin,
    required this.endMargin,
    required this.startArrowCenter,
    required this.endArrowCenter,
    required this.startPoint,
    required this.endPoint,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pathPoints.hashCode ^
      pathType.hashCode ^
      startTangent.hashCode ^
      endTangent.hashCode ^
      bodyWidths.hashCode ^
      bodyType.hashCode ^
      startEndpoint.hashCode ^
      endEndpoint.hashCode ^
      startDirection.hashCode ^
      endDirection.hashCode ^
      labelPosition.hashCode ^
      labelAnchor.hashCode ^
      bundleId.hashCode ^
      bundleOffset.hashCode ^
      hitTestPoints.hashCode ^
      dependsOnNodes.hashCode ^
      bbox.hashCode ^
      startMargin.hashCode ^
      endMargin.hashCode ^
      startArrowCenter.hashCode ^
      endArrowCenter.hashCode ^
      startPoint.hashCode ^
      endPoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComputedRelation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pathPoints == other.pathPoints &&
          pathType == other.pathType &&
          startTangent == other.startTangent &&
          endTangent == other.endTangent &&
          bodyWidths == other.bodyWidths &&
          bodyType == other.bodyType &&
          startEndpoint == other.startEndpoint &&
          endEndpoint == other.endEndpoint &&
          startDirection == other.startDirection &&
          endDirection == other.endDirection &&
          labelPosition == other.labelPosition &&
          labelAnchor == other.labelAnchor &&
          bundleId == other.bundleId &&
          bundleOffset == other.bundleOffset &&
          hitTestPoints == other.hitTestPoints &&
          dependsOnNodes == other.dependsOnNodes &&
          bbox == other.bbox &&
          startMargin == other.startMargin &&
          endMargin == other.endMargin &&
          startArrowCenter == other.startArrowCenter &&
          endArrowCenter == other.endArrowCenter &&
          startPoint == other.startPoint &&
          endPoint == other.endPoint;
}

enum LabelAnchor { center, left, right }

enum PathType {
  straight,
  cubicBezier,
  quadraticBezier,
  orthogonal,
  circularArc,
  sineWave,
}
