// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../enums.dart';
import '../id.dart';
import '../traits.dart';
import 'config.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class ComputedRelation {
  final TypedRecordId id;
  final List<Point> pathPoints;
  final PathType pathType;
  final Point startTangent;
  final Point endTangent;
  final Float64List bodyWidths;
  final BodyType bodyType;
  final EndpointShape startEndpoint;
  final EndpointShape endEndpoint;
  final double startDirection;
  final double endDirection;
  final Point labelPosition;
  final LabelAnchor labelAnchor;
  final Rect bbox;
  final Point startPoint;
  final Point endPoint;
  final Point startArrowCenter;
  final Point endArrowCenter;
  final double startMargin;
  final double endMargin;
  final List<TypedRecordId> dependsOnNodes;
  final String? bundleId;
  final double? bundleOffset;
  final List<Point> controlPoints;
  final Float64List knots;
  final List<String> nudgeColors;
  final List<Point> hitTestPoints;
  final bool composeActive;

  const ComputedRelation({
    required this.id,
    required this.pathPoints,
    required this.pathType,
    required this.startTangent,
    required this.endTangent,
    required this.bodyWidths,
    required this.bodyType,
    required this.startEndpoint,
    required this.endEndpoint,
    required this.startDirection,
    required this.endDirection,
    required this.labelPosition,
    required this.labelAnchor,
    required this.bbox,
    required this.startPoint,
    required this.endPoint,
    required this.startArrowCenter,
    required this.endArrowCenter,
    required this.startMargin,
    required this.endMargin,
    required this.dependsOnNodes,
    this.bundleId,
    this.bundleOffset,
    required this.controlPoints,
    required this.knots,
    required this.nudgeColors,
    required this.hitTestPoints,
    required this.composeActive,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pathPoints.hashCode ^
      pathType.hashCode ^
      startTangent.hashCode ^
      endTangent.hashCode ^
      bodyWidths.hashCode ^
      bodyType.hashCode ^
      startEndpoint.hashCode ^
      endEndpoint.hashCode ^
      startDirection.hashCode ^
      endDirection.hashCode ^
      labelPosition.hashCode ^
      labelAnchor.hashCode ^
      bbox.hashCode ^
      startPoint.hashCode ^
      endPoint.hashCode ^
      startArrowCenter.hashCode ^
      endArrowCenter.hashCode ^
      startMargin.hashCode ^
      endMargin.hashCode ^
      dependsOnNodes.hashCode ^
      bundleId.hashCode ^
      bundleOffset.hashCode ^
      controlPoints.hashCode ^
      knots.hashCode ^
      nudgeColors.hashCode ^
      hitTestPoints.hashCode ^
      composeActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComputedRelation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pathPoints == other.pathPoints &&
          pathType == other.pathType &&
          startTangent == other.startTangent &&
          endTangent == other.endTangent &&
          bodyWidths == other.bodyWidths &&
          bodyType == other.bodyType &&
          startEndpoint == other.startEndpoint &&
          endEndpoint == other.endEndpoint &&
          startDirection == other.startDirection &&
          endDirection == other.endDirection &&
          labelPosition == other.labelPosition &&
          labelAnchor == other.labelAnchor &&
          bbox == other.bbox &&
          startPoint == other.startPoint &&
          endPoint == other.endPoint &&
          startArrowCenter == other.startArrowCenter &&
          endArrowCenter == other.endArrowCenter &&
          startMargin == other.startMargin &&
          endMargin == other.endMargin &&
          dependsOnNodes == other.dependsOnNodes &&
          bundleId == other.bundleId &&
          bundleOffset == other.bundleOffset &&
          controlPoints == other.controlPoints &&
          knots == other.knots &&
          nudgeColors == other.nudgeColors &&
          hitTestPoints == other.hitTestPoints &&
          composeActive == other.composeActive;
}

enum LabelAnchor { center, left, right }

enum PathType { straight, bSpline, orthogonal, bezier, sineWave }
