// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BodyConfig {
  final BodyType defaultType;
  final double taperStartWidth;
  final double taperEndWidth;
  final double widthModulateAmplitude;
  final double widthModulateFrequency;

  const BodyConfig({
    required this.defaultType,
    required this.taperStartWidth,
    required this.taperEndWidth,
    required this.widthModulateAmplitude,
    required this.widthModulateFrequency,
  });

  @override
  int get hashCode =>
      defaultType.hashCode ^
      taperStartWidth.hashCode ^
      taperEndWidth.hashCode ^
      widthModulateAmplitude.hashCode ^
      widthModulateFrequency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BodyConfig &&
          runtimeType == other.runtimeType &&
          defaultType == other.defaultType &&
          taperStartWidth == other.taperStartWidth &&
          taperEndWidth == other.taperEndWidth &&
          widthModulateAmplitude == other.widthModulateAmplitude &&
          widthModulateFrequency == other.widthModulateFrequency;
}

enum BodyType { uniform, taper, widthModulate, bundled }

class BundlingConfig {
  final BundlingMode mode;
  final double threshold;

  const BundlingConfig({required this.mode, required this.threshold});

  @override
  int get hashCode => mode.hashCode ^ threshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BundlingConfig &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          threshold == other.threshold;
}

enum BundlingMode { proximity, sharedEndpoint, none }

class EndpointConfig {
  final EndpointShapeType defaultStartShape;
  final EndpointShapeType defaultEndShape;
  final double arrowSize;

  const EndpointConfig({
    required this.defaultStartShape,
    required this.defaultEndShape,
    required this.arrowSize,
  });

  @override
  int get hashCode =>
      defaultStartShape.hashCode ^
      defaultEndShape.hashCode ^
      arrowSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EndpointConfig &&
          runtimeType == other.runtimeType &&
          defaultStartShape == other.defaultStartShape &&
          defaultEndShape == other.defaultEndShape &&
          arrowSize == other.arrowSize;
}

enum EndpointShapeType { none, arrow, openArrow, circle, diamond, square }

class NudgingConfig {
  final bool enabled;
  final double distance;

  const NudgingConfig({required this.enabled, required this.distance});

  @override
  int get hashCode => enabled.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NudgingConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          distance == other.distance;
}

class RelationEngineConfig {
  final RoutingConfig routing;
  final NudgingConfig nudging;
  final BundlingConfig bundling;
  final bool crossingMinimization;
  final bool incrementalMode;
  final BodyConfig body;
  final EndpointConfig endpoint;
  final SnakeConfig snake;

  const RelationEngineConfig({
    required this.routing,
    required this.nudging,
    required this.bundling,
    required this.crossingMinimization,
    required this.incrementalMode,
    required this.body,
    required this.endpoint,
    required this.snake,
  });

  @override
  int get hashCode =>
      routing.hashCode ^
      nudging.hashCode ^
      bundling.hashCode ^
      crossingMinimization.hashCode ^
      incrementalMode.hashCode ^
      body.hashCode ^
      endpoint.hashCode ^
      snake.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationEngineConfig &&
          runtimeType == other.runtimeType &&
          routing == other.routing &&
          nudging == other.nudging &&
          bundling == other.bundling &&
          crossingMinimization == other.crossingMinimization &&
          incrementalMode == other.incrementalMode &&
          body == other.body &&
          endpoint == other.endpoint &&
          snake == other.snake;
}

class RoutingConfig {
  final RoutingMode routingMode;
  final double obstacleMargin;
  final double cornerRadius;
  final double bezierCurvature;
  final double bezierProjectionFactor;
  final double bezierClampMin;
  final double bezierClampMax;

  const RoutingConfig({
    required this.routingMode,
    required this.obstacleMargin,
    required this.cornerRadius,
    required this.bezierCurvature,
    required this.bezierProjectionFactor,
    required this.bezierClampMin,
    required this.bezierClampMax,
  });

  @override
  int get hashCode =>
      routingMode.hashCode ^
      obstacleMargin.hashCode ^
      cornerRadius.hashCode ^
      bezierCurvature.hashCode ^
      bezierProjectionFactor.hashCode ^
      bezierClampMin.hashCode ^
      bezierClampMax.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingConfig &&
          runtimeType == other.runtimeType &&
          routingMode == other.routingMode &&
          obstacleMargin == other.obstacleMargin &&
          cornerRadius == other.cornerRadius &&
          bezierCurvature == other.bezierCurvature &&
          bezierProjectionFactor == other.bezierProjectionFactor &&
          bezierClampMin == other.bezierClampMin &&
          bezierClampMax == other.bezierClampMax;
}

enum RoutingMode { polyline, bezier, orthogonal, circularArc, sineWave }

class SnakeConfig {
  final double amplitude;
  final double frequency;
  final bool obstacleAvoidance;

  const SnakeConfig({
    required this.amplitude,
    required this.frequency,
    required this.obstacleAvoidance,
  });

  @override
  int get hashCode =>
      amplitude.hashCode ^ frequency.hashCode ^ obstacleAvoidance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnakeConfig &&
          runtimeType == other.runtimeType &&
          amplitude == other.amplitude &&
          frequency == other.frequency &&
          obstacleAvoidance == other.obstacleAvoidance;
}
