// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum BodyType { uniform, taper, widthModulate, bundled }

enum BundlingMode { proximity, sharedEndpoint, none }

enum EndpointShapeType { none, arrow, openArrow, circle, diamond, square }

class RelationEngineConfig {
  final RoutingMode routingMode;
  final double obstacleMargin;
  final double cornerRadius;
  final bool incrementalMode;
  final bool nudgingEnabled;
  final double nudgingDistance;
  final BundlingMode bundlingMode;
  final double bundlingThreshold;
  final bool crossingMinimization;
  final double bezierCurvature;
  final double bezierProjectionFactor;
  final double bezierClampMin;
  final double bezierClampMax;
  final BodyType defaultBodyType;
  final double taperStartWidth;
  final double taperEndWidth;
  final double widthModulateAmplitude;
  final double widthModulateFrequency;
  final EndpointShapeType defaultStartShape;
  final EndpointShapeType defaultEndShape;
  final double arrowSize;
  final double snakeAmplitude;
  final double snakeFrequency;
  final bool snakeObstacleAvoidance;

  const RelationEngineConfig({
    required this.routingMode,
    required this.obstacleMargin,
    required this.cornerRadius,
    required this.incrementalMode,
    required this.nudgingEnabled,
    required this.nudgingDistance,
    required this.bundlingMode,
    required this.bundlingThreshold,
    required this.crossingMinimization,
    required this.bezierCurvature,
    required this.bezierProjectionFactor,
    required this.bezierClampMin,
    required this.bezierClampMax,
    required this.defaultBodyType,
    required this.taperStartWidth,
    required this.taperEndWidth,
    required this.widthModulateAmplitude,
    required this.widthModulateFrequency,
    required this.defaultStartShape,
    required this.defaultEndShape,
    required this.arrowSize,
    required this.snakeAmplitude,
    required this.snakeFrequency,
    required this.snakeObstacleAvoidance,
  });

  @override
  int get hashCode =>
      routingMode.hashCode ^
      obstacleMargin.hashCode ^
      cornerRadius.hashCode ^
      incrementalMode.hashCode ^
      nudgingEnabled.hashCode ^
      nudgingDistance.hashCode ^
      bundlingMode.hashCode ^
      bundlingThreshold.hashCode ^
      crossingMinimization.hashCode ^
      bezierCurvature.hashCode ^
      bezierProjectionFactor.hashCode ^
      bezierClampMin.hashCode ^
      bezierClampMax.hashCode ^
      defaultBodyType.hashCode ^
      taperStartWidth.hashCode ^
      taperEndWidth.hashCode ^
      widthModulateAmplitude.hashCode ^
      widthModulateFrequency.hashCode ^
      defaultStartShape.hashCode ^
      defaultEndShape.hashCode ^
      arrowSize.hashCode ^
      snakeAmplitude.hashCode ^
      snakeFrequency.hashCode ^
      snakeObstacleAvoidance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationEngineConfig &&
          runtimeType == other.runtimeType &&
          routingMode == other.routingMode &&
          obstacleMargin == other.obstacleMargin &&
          cornerRadius == other.cornerRadius &&
          incrementalMode == other.incrementalMode &&
          nudgingEnabled == other.nudgingEnabled &&
          nudgingDistance == other.nudgingDistance &&
          bundlingMode == other.bundlingMode &&
          bundlingThreshold == other.bundlingThreshold &&
          crossingMinimization == other.crossingMinimization &&
          bezierCurvature == other.bezierCurvature &&
          bezierProjectionFactor == other.bezierProjectionFactor &&
          bezierClampMin == other.bezierClampMin &&
          bezierClampMax == other.bezierClampMax &&
          defaultBodyType == other.defaultBodyType &&
          taperStartWidth == other.taperStartWidth &&
          taperEndWidth == other.taperEndWidth &&
          widthModulateAmplitude == other.widthModulateAmplitude &&
          widthModulateFrequency == other.widthModulateFrequency &&
          defaultStartShape == other.defaultStartShape &&
          defaultEndShape == other.defaultEndShape &&
          arrowSize == other.arrowSize &&
          snakeAmplitude == other.snakeAmplitude &&
          snakeFrequency == other.snakeFrequency &&
          snakeObstacleAvoidance == other.snakeObstacleAvoidance;
}

enum RoutingMode { polyline, bezier, orthogonal }
