// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../styles.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class InputEdge {
  final String id;
  final String fromNodeId;
  final String toNodeId;
  final PortSide? fromSide;
  final PortSide? toSide;
  final String? strategyType;

  const InputEdge({
    required this.id,
    required this.fromNodeId,
    required this.toNodeId,
    this.fromSide,
    this.toSide,
    this.strategyType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      fromNodeId.hashCode ^
      toNodeId.hashCode ^
      fromSide.hashCode ^
      toSide.hashCode ^
      strategyType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputEdge &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fromNodeId == other.fromNodeId &&
          toNodeId == other.toNodeId &&
          fromSide == other.fromSide &&
          toSide == other.toSide &&
          strategyType == other.strategyType;
}

class InputNode {
  final String id;
  final double x;
  final double y;
  final double width;
  final double height;

  const InputNode({
    required this.id,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      id.hashCode ^ x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}
