// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ConvergenceCriteria {
  final int maxIterations;
  final double energyThreshold;
  final double displacementThreshold;
  final int oscillationWindow;

  const ConvergenceCriteria({
    required this.maxIterations,
    required this.energyThreshold,
    required this.displacementThreshold,
    required this.oscillationWindow,
  });

  @override
  int get hashCode =>
      maxIterations.hashCode ^
      energyThreshold.hashCode ^
      displacementThreshold.hashCode ^
      oscillationWindow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvergenceCriteria &&
          runtimeType == other.runtimeType &&
          maxIterations == other.maxIterations &&
          energyThreshold == other.energyThreshold &&
          displacementThreshold == other.displacementThreshold &&
          oscillationWindow == other.oscillationWindow;
}

class ForceConfig {
  final double repulsionConstant;
  final double springConstant;
  final double idealLinkDistance;
  final double collisionStrength;
  final double baseMargin;
  final double marginScale;
  final double wallStrength;
  final double wallPadding;
  final double damping;
  final double alphaDecay;
  final double alphaMin;

  const ForceConfig({
    required this.repulsionConstant,
    required this.springConstant,
    required this.idealLinkDistance,
    required this.collisionStrength,
    required this.baseMargin,
    required this.marginScale,
    required this.wallStrength,
    required this.wallPadding,
    required this.damping,
    required this.alphaDecay,
    required this.alphaMin,
  });

  @override
  int get hashCode =>
      repulsionConstant.hashCode ^
      springConstant.hashCode ^
      idealLinkDistance.hashCode ^
      collisionStrength.hashCode ^
      baseMargin.hashCode ^
      marginScale.hashCode ^
      wallStrength.hashCode ^
      wallPadding.hashCode ^
      damping.hashCode ^
      alphaDecay.hashCode ^
      alphaMin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForceConfig &&
          runtimeType == other.runtimeType &&
          repulsionConstant == other.repulsionConstant &&
          springConstant == other.springConstant &&
          idealLinkDistance == other.idealLinkDistance &&
          collisionStrength == other.collisionStrength &&
          baseMargin == other.baseMargin &&
          marginScale == other.marginScale &&
          wallStrength == other.wallStrength &&
          wallPadding == other.wallPadding &&
          damping == other.damping &&
          alphaDecay == other.alphaDecay &&
          alphaMin == other.alphaMin;
}

class LayoutConfig {
  final ForceConfig force;
  final ConvergenceCriteria convergence;
  final int batchSize;

  const LayoutConfig({
    required this.force,
    required this.convergence,
    required this.batchSize,
  });

  @override
  int get hashCode =>
      force.hashCode ^ convergence.hashCode ^ batchSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutConfig &&
          runtimeType == other.runtimeType &&
          force == other.force &&
          convergence == other.convergence &&
          batchSize == other.batchSize;
}
