// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/id.dart';
import '../domain/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class LayoutPatch {
  final TypedRecordId id;
  final double x;
  final double y;

  const LayoutPatch({required this.id, required this.x, required this.y});

  @override
  int get hashCode => id.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutPatch &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          x == other.x &&
          y == other.y;
}

class LayoutTickResult {
  final List<LayoutPatch> positionPatches;
  final bool converged;
  final int iteration;
  final double energy;

  const LayoutTickResult({
    required this.positionPatches,
    required this.converged,
    required this.iteration,
    required this.energy,
  });

  @override
  int get hashCode =>
      positionPatches.hashCode ^
      converged.hashCode ^
      iteration.hashCode ^
      energy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutTickResult &&
          runtimeType == other.runtimeType &&
          positionPatches == other.positionPatches &&
          converged == other.converged &&
          iteration == other.iteration &&
          energy == other.energy;
}
