// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Attachment {
  final String id;
  final String hash;
  final String name;
  final String mimeType;
  final PlatformInt64 byteSize;
  final int? width;
  final int? height;
  final int? durationMs;

  const Attachment({
    required this.id,
    required this.hash,
    required this.name,
    required this.mimeType,
    required this.byteSize,
    this.width,
    this.height,
    this.durationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      hash.hashCode ^
      name.hashCode ^
      mimeType.hashCode ^
      byteSize.hashCode ^
      width.hashCode ^
      height.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          hash == other.hash &&
          name == other.name &&
          mimeType == other.mimeType &&
          byteSize == other.byteSize &&
          width == other.width &&
          height == other.height &&
          durationMs == other.durationMs;
}

class BoundingBox {
  final double minX;
  final double minY;
  final double maxX;
  final double maxY;

  const BoundingBox({
    required this.minX,
    required this.minY,
    required this.maxX,
    required this.maxY,
  });

  @override
  int get hashCode =>
      minX.hashCode ^ minY.hashCode ^ maxX.hashCode ^ maxY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoundingBox &&
          runtimeType == other.runtimeType &&
          minX == other.minX &&
          minY == other.minY &&
          maxX == other.maxX &&
          maxY == other.maxY;
}

class Comment {
  final String text;
  final PlatformInt64 createdAt;

  const Comment({required this.text, required this.createdAt});

  @override
  int get hashCode => text.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Comment &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          createdAt == other.createdAt;
}

class Coordinates {
  final int x;
  final int y;

  const Coordinates({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Coordinates &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

enum DisplayMode { importance, leveling }

class MapDescriptor {
  final String id;
  final String name;
  final String storagePath;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 modifiedAtMs;
  final PlatformInt64 accessedAtMs;

  const MapDescriptor({
    required this.id,
    required this.name,
    required this.storagePath,
    required this.createdAtMs,
    required this.modifiedAtMs,
    required this.accessedAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      storagePath.hashCode ^
      createdAtMs.hashCode ^
      modifiedAtMs.hashCode ^
      accessedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          storagePath == other.storagePath &&
          createdAtMs == other.createdAtMs &&
          modifiedAtMs == other.modifiedAtMs &&
          accessedAtMs == other.accessedAtMs;
}

class Size {
  final int width;
  final int height;

  const Size({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Size &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class ViewportState {
  final double xOffset;
  final double yOffset;
  final double zoomLevel;
  final String activeView;

  const ViewportState({
    required this.xOffset,
    required this.yOffset,
    required this.zoomLevel,
    required this.activeView,
  });

  @override
  int get hashCode =>
      xOffset.hashCode ^
      yOffset.hashCode ^
      zoomLevel.hashCode ^
      activeView.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportState &&
          runtimeType == other.runtimeType &&
          xOffset == other.xOffset &&
          yOffset == other.yOffset &&
          zoomLevel == other.zoomLevel &&
          activeView == other.activeView;
}
