// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Block-level attributes
class BlockAttrs {
  final int? level;
  final String? language;

  const BlockAttrs({this.level, this.language});

  @override
  int get hashCode => level.hashCode ^ language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockAttrs &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          language == other.language;
}

enum BlockType {
  paragraph,
  heading,
  bulletList,
  orderedList,
  codeBlock,
  blockquote,
}

/// The mathematical boundary object for elastic canvas constraints.
/// Uses i32 to match the existing Coordinates type in the codebase.
class BoundingBox {
  final int minX;
  final int minY;
  final int maxX;
  final int maxY;

  const BoundingBox({
    required this.minX,
    required this.minY,
    required this.maxX,
    required this.maxY,
  });

  @override
  int get hashCode =>
      minX.hashCode ^ minY.hashCode ^ maxX.hashCode ^ maxY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoundingBox &&
          runtimeType == other.runtimeType &&
          minX == other.minX &&
          minY == other.minY &&
          maxX == other.maxX &&
          maxY == other.maxY;
}

class Comment {
  final String text;
  final PlatformInt64 createdAt;

  const Comment({required this.text, required this.createdAt});

  @override
  int get hashCode => text.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Comment &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          createdAt == other.createdAt;
}

/// Primary source of truth for node content.
/// The `text` field is derived from `blocks` for search indexing in SurrealDB.
class Content {
  /// Plain text projection - used for search indexing.
  final String text;

  /// Native block structure - queryable logic
  final List<ContentBlock> blocks;

  const Content({required this.text, required this.blocks});

  @override
  int get hashCode => text.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Content &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          blocks == other.blocks;
}

/// Block-level content (paragraphs, headings, lists)
class ContentBlock {
  final BlockType blockType;
  final List<InlineElement> content;
  final BlockAttrs? attrs;

  const ContentBlock({
    required this.blockType,
    required this.content,
    this.attrs,
  });

  @override
  int get hashCode => blockType.hashCode ^ content.hashCode ^ attrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentBlock &&
          runtimeType == other.runtimeType &&
          blockType == other.blockType &&
          content == other.content &&
          attrs == other.attrs;
}

class Coordinates {
  final int x;
  final int y;
  final int z;

  const Coordinates({required this.x, required this.y, required this.z});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ z.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Coordinates &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          z == other.z;
}

/// Inline content with optional formatting marks
class InlineElement {
  final InlineType inlineType;
  final String text;
  final List<TextMark>? marks;

  const InlineElement({
    required this.inlineType,
    required this.text,
    this.marks,
  });

  @override
  int get hashCode => inlineType.hashCode ^ text.hashCode ^ marks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InlineElement &&
          runtimeType == other.runtimeType &&
          inlineType == other.inlineType &&
          text == other.text &&
          marks == other.marks;
}

enum InlineType { text, hardBreak }

class MapConfig {
  final String mapName;
  final ViewportState viewportState;
  final String? activeThemeId;

  const MapConfig({
    required this.mapName,
    required this.viewportState,
    this.activeThemeId,
  });

  @override
  int get hashCode =>
      mapName.hashCode ^ viewportState.hashCode ^ activeThemeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapConfig &&
          runtimeType == other.runtimeType &&
          mapName == other.mapName &&
          viewportState == other.viewportState &&
          activeThemeId == other.activeThemeId;
}

/// Mark-level attributes
class MarkAttrs {
  final String? href;

  const MarkAttrs({this.href});

  @override
  int get hashCode => href.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkAttrs &&
          runtimeType == other.runtimeType &&
          href == other.href;
}

enum MarkType { bold, italic, underline, strikethrough, code, link }

/// Formatting mark (bold, italic, link, etc.)
class TextMark {
  final MarkType markType;
  final MarkAttrs? attrs;

  const TextMark({required this.markType, this.attrs});

  @override
  int get hashCode => markType.hashCode ^ attrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextMark &&
          runtimeType == other.runtimeType &&
          markType == other.markType &&
          attrs == other.attrs;
}

class Theme {
  final String? id;
  final String name;
  final String config;

  const Theme({this.id, required this.name, required this.config});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ config.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Theme &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          config == other.config;
}

class ViewportState {
  final double xOffset;
  final double yOffset;
  final double zoomLevel;
  final String activeView;

  const ViewportState({
    required this.xOffset,
    required this.yOffset,
    required this.zoomLevel,
    required this.activeView,
  });

  @override
  int get hashCode =>
      xOffset.hashCode ^
      yOffset.hashCode ^
      zoomLevel.hashCode ^
      activeView.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportState &&
          runtimeType == other.runtimeType &&
          xOffset == other.xOffset &&
          yOffset == other.yOffset &&
          zoomLevel == other.zoomLevel &&
          activeView == other.activeView;
}
