// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MapConfig {
  final String mapName;
  final ViewportState viewportState;
  final ThemeConfig theme;

  const MapConfig({
    required this.mapName,
    required this.viewportState,
    required this.theme,
  });

  @override
  int get hashCode =>
      mapName.hashCode ^ viewportState.hashCode ^ theme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapConfig &&
          runtimeType == other.runtimeType &&
          mapName == other.mapName &&
          viewportState == other.viewportState &&
          theme == other.theme;
}

class StyleProfile {
  final String shape;
  final String bgColor;
  final String strokeColor;
  final double strokeWidth;
  final String fontFamily;

  const StyleProfile({
    required this.shape,
    required this.bgColor,
    required this.strokeColor,
    required this.strokeWidth,
    required this.fontFamily,
  });

  @override
  int get hashCode =>
      shape.hashCode ^
      bgColor.hashCode ^
      strokeColor.hashCode ^
      strokeWidth.hashCode ^
      fontFamily.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StyleProfile &&
          runtimeType == other.runtimeType &&
          shape == other.shape &&
          bgColor == other.bgColor &&
          strokeColor == other.strokeColor &&
          strokeWidth == other.strokeWidth &&
          fontFamily == other.fontFamily;
}

class ThemeConfig {
  final String name;
  final StyleProfile globalDefault;
  final Map<String, StyleProfile> typeDefinitions;

  const ThemeConfig({
    required this.name,
    required this.globalDefault,
    required this.typeDefinitions,
  });

  @override
  int get hashCode =>
      name.hashCode ^ globalDefault.hashCode ^ typeDefinitions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemeConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          globalDefault == other.globalDefault &&
          typeDefinitions == other.typeDefinitions;
}

class ViewportState {
  final double xOffset;
  final double yOffset;
  final double zoomLevel;
  final String activeView;

  const ViewportState({
    required this.xOffset,
    required this.yOffset,
    required this.zoomLevel,
    required this.activeView,
  });

  @override
  int get hashCode =>
      xOffset.hashCode ^
      yOffset.hashCode ^
      zoomLevel.hashCode ^
      activeView.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportState &&
          runtimeType == other.runtimeType &&
          xOffset == other.xOffset &&
          yOffset == other.yOffset &&
          zoomLevel == other.zoomLevel &&
          activeView == other.activeView;
}
