// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'contents.dart';
import 'enums.dart';
import 'id.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'styles.dart';
import 'tags.dart';
import 'traits.dart';
part 'entity.freezed.dart';

@freezed
sealed class Nodes with _$Nodes {
  const Nodes._();

  const factory Nodes.iNode(INode field0) = Nodes_INode;
  const factory Nodes.taskNode(TaskNode field0) = Nodes_TaskNode;
  const factory Nodes.interNode(InterNode field0) = Nodes_InterNode;
  const factory Nodes.commentNode(CommentNode field0) = Nodes_CommentNode;
  const factory Nodes.drawingNode(DrawingNode field0) = Nodes_DrawingNode;
  const factory Nodes.shapeNode(ShapeNode field0) = Nodes_ShapeNode;
  const factory Nodes.frameNode(FrameNode field0) = Nodes_FrameNode;
  const factory Nodes.mediaNode(MediaNode field0) = Nodes_MediaNode;
}
