// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum BrushType { pencil, highlighter, eraser, calligraphy }

enum EndpointShape { none, arrow, openArrow, circle, diamond, square }

enum MediaType { image, video, audio, pdf }

enum ShapeType { rectangle, circle, diamond, triangle, star, pill }

enum TaskState { todo, inProgress, done, blocked, cancelled }
