// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'traits.dart';

/// Unified record identifier across all tiers. 17 bytes on stack, 0 heap allocations.
class TypedRecordId {
  final TableKind table;
  final UuidValue key;

  const TypedRecordId({required this.table, required this.key});

  @override
  int get hashCode => table.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypedRecordId &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          key == other.key;
}
