// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'contents.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'styles.dart';
import 'tags.dart';
part 'nodes.freezed.dart';

class CommentNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String text;
  final Coordinates position;
  final Size size;
  final String layer;

  const CommentNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.text,
    required this.position,
    required this.size,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      text.hashCode ^
      position.hashCode ^
      size.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          text == other.text &&
          position == other.position &&
          size == other.size &&
          layer == other.layer;
}

class DrawingNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final List<String> paths;
  final Coordinates position;
  final String layer;

  const DrawingNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.paths,
    required this.position,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      paths.hashCode ^
      position.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawingNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          paths == other.paths &&
          position == other.position &&
          layer == other.layer;
}

class FrameNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String title;
  final NodeStyle? style;
  final Coordinates position;
  final Size size;
  final String layer;

  const FrameNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.title,
    this.style,
    required this.position,
    required this.size,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      title.hashCode ^
      style.hashCode ^
      position.hashCode ^
      size.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          title == other.title &&
          style == other.style &&
          position == other.position &&
          size == other.size &&
          layer == other.layer;
}

class INode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final Content content;
  final NodeStyle? style;
  final NodeStyle? resolvedStyle;
  final NodeLayout? layout;
  final NodeLayout? resolvedLayout;
  final String layer;
  final Coordinates position;
  final Size size;
  final int lineCount;
  final bool expandable;
  final bool isExpanded;
  final bool locked;
  final List<TagEdge> tags;
  final List<String> aliases;
  final List<Comment> comments;
  final String? attachment;
  final int significance;

  const INode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.content,
    this.style,
    this.resolvedStyle,
    this.layout,
    this.resolvedLayout,
    required this.layer,
    required this.position,
    required this.size,
    required this.lineCount,
    required this.expandable,
    required this.isExpanded,
    required this.locked,
    required this.tags,
    required this.aliases,
    required this.comments,
    this.attachment,
    required this.significance,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      content.hashCode ^
      style.hashCode ^
      resolvedStyle.hashCode ^
      layout.hashCode ^
      resolvedLayout.hashCode ^
      layer.hashCode ^
      position.hashCode ^
      size.hashCode ^
      lineCount.hashCode ^
      expandable.hashCode ^
      isExpanded.hashCode ^
      locked.hashCode ^
      tags.hashCode ^
      aliases.hashCode ^
      comments.hashCode ^
      attachment.hashCode ^
      significance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is INode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          content == other.content &&
          style == other.style &&
          resolvedStyle == other.resolvedStyle &&
          layout == other.layout &&
          resolvedLayout == other.resolvedLayout &&
          layer == other.layer &&
          position == other.position &&
          size == other.size &&
          lineCount == other.lineCount &&
          expandable == other.expandable &&
          isExpanded == other.isExpanded &&
          locked == other.locked &&
          tags == other.tags &&
          aliases == other.aliases &&
          comments == other.comments &&
          attachment == other.attachment &&
          significance == other.significance;
}

class InterNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final Coordinates position;
  final String? style;
  final String verb;
  final String? behavioralFeatures;
  final String layer;

  const InterNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.position,
    this.style,
    required this.verb,
    this.behavioralFeatures,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      position.hashCode ^
      style.hashCode ^
      verb.hashCode ^
      behavioralFeatures.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InterNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          position == other.position &&
          style == other.style &&
          verb == other.verb &&
          behavioralFeatures == other.behavioralFeatures &&
          layer == other.layer;
}

class MediaNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String sourceUrl;
  final String mediaType;
  final Coordinates position;
  final Size size;
  final String layer;

  const MediaNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.sourceUrl,
    required this.mediaType,
    required this.position,
    required this.size,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sourceUrl.hashCode ^
      mediaType.hashCode ^
      position.hashCode ^
      size.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sourceUrl == other.sourceUrl &&
          mediaType == other.mediaType &&
          position == other.position &&
          size == other.size &&
          layer == other.layer;
}

@freezed
sealed class Nodes with _$Nodes {
  const Nodes._();

  const factory Nodes.iNode(INode field0) = Nodes_INode;
  const factory Nodes.taskNode(TaskNode field0) = Nodes_TaskNode;
  const factory Nodes.interNode(InterNode field0) = Nodes_InterNode;
  const factory Nodes.commentNode(CommentNode field0) = Nodes_CommentNode;
  const factory Nodes.drawingNode(DrawingNode field0) = Nodes_DrawingNode;
  const factory Nodes.shapeNode(ShapeNode field0) = Nodes_ShapeNode;
  const factory Nodes.frameNode(FrameNode field0) = Nodes_FrameNode;
  const factory Nodes.mediaNode(MediaNode field0) = Nodes_MediaNode;
}

class ShapeNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String shapeType;
  final NodeStyle? style;
  final Coordinates position;
  final Size size;
  final String layer;

  const ShapeNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.shapeType,
    this.style,
    required this.position,
    required this.size,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      shapeType.hashCode ^
      style.hashCode ^
      position.hashCode ^
      size.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          shapeType == other.shapeType &&
          style == other.style &&
          position == other.position &&
          size == other.size &&
          layer == other.layer;
}

class TaskNode {
  final RecordStrings id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final Content content;
  final PlatformInt64? dueDate;
  final String state;
  final Coordinates position;
  final Size size;
  final bool expandable;
  final bool isExpanded;
  final String layer;
  final NodeStyle? style;
  final NodeStyle? resolvedStyle;
  final NodeLayout? layout;
  final NodeLayout? resolvedLayout;
  final int significance;

  const TaskNode({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.content,
    this.dueDate,
    required this.state,
    required this.position,
    required this.size,
    required this.expandable,
    required this.isExpanded,
    required this.layer,
    this.style,
    this.resolvedStyle,
    this.layout,
    this.resolvedLayout,
    required this.significance,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      content.hashCode ^
      dueDate.hashCode ^
      state.hashCode ^
      position.hashCode ^
      size.hashCode ^
      expandable.hashCode ^
      isExpanded.hashCode ^
      layer.hashCode ^
      style.hashCode ^
      resolvedStyle.hashCode ^
      layout.hashCode ^
      resolvedLayout.hashCode ^
      significance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          content == other.content &&
          dueDate == other.dueDate &&
          state == other.state &&
          position == other.position &&
          size == other.size &&
          expandable == other.expandable &&
          isExpanded == other.isExpanded &&
          layer == other.layer &&
          style == other.style &&
          resolvedStyle == other.resolvedStyle &&
          layout == other.layout &&
          resolvedLayout == other.resolvedLayout &&
          significance == other.significance;
}
