// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'nodes.freezed.dart';

class INode {
  final String? id;
  final Content content;
  final String? aesthetics;
  final Coordinates position;
  final bool locked;
  final List<String> tags;
  final List<String> aliases;
  final List<Comment> comments;
  final String? attachment;
  final int significance;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const INode({
    this.id,
    required this.content,
    this.aesthetics,
    required this.position,
    required this.locked,
    required this.tags,
    required this.aliases,
    required this.comments,
    this.attachment,
    required this.significance,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      aesthetics.hashCode ^
      position.hashCode ^
      locked.hashCode ^
      tags.hashCode ^
      aliases.hashCode ^
      comments.hashCode ^
      attachment.hashCode ^
      significance.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is INode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          aesthetics == other.aesthetics &&
          position == other.position &&
          locked == other.locked &&
          tags == other.tags &&
          aliases == other.aliases &&
          comments == other.comments &&
          attachment == other.attachment &&
          significance == other.significance &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class InterNode {
  final String? id;
  final String verb;
  final String? behavioralFeatures;
  final Coordinates position;
  final String? aesthetics;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const InterNode({
    this.id,
    required this.verb,
    this.behavioralFeatures,
    required this.position,
    this.aesthetics,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      verb.hashCode ^
      behavioralFeatures.hashCode ^
      position.hashCode ^
      aesthetics.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InterNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          verb == other.verb &&
          behavioralFeatures == other.behavioralFeatures &&
          position == other.position &&
          aesthetics == other.aesthetics &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

@freezed
sealed class NodeInput with _$NodeInput {
  const NodeInput._();

  const factory NodeInput.info(INode field0) = NodeInput_Info;
  const factory NodeInput.task(TaskNode field0) = NodeInput_Task;
  const factory NodeInput.inter(InterNode field0) = NodeInput_Inter;
}

@freezed
sealed class NodeOutput with _$NodeOutput {
  const NodeOutput._();

  const factory NodeOutput.info(INode field0) = NodeOutput_Info;
  const factory NodeOutput.task(TaskNode field0) = NodeOutput_Task;
  const factory NodeOutput.inter(InterNode field0) = NodeOutput_Inter;
}

class TaskNode {
  final String? id;
  final Content content;
  final PlatformInt64? dueDate;
  final String state;
  final Coordinates position;
  final String? aesthetics;
  final int significance;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const TaskNode({
    this.id,
    required this.content,
    this.dueDate,
    required this.state,
    required this.position,
    this.aesthetics,
    required this.significance,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      dueDate.hashCode ^
      state.hashCode ^
      position.hashCode ^
      aesthetics.hashCode ^
      significance.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          dueDate == other.dueDate &&
          state == other.state &&
          position == other.position &&
          aesthetics == other.aesthetics &&
          significance == other.significance &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
