// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../relation_engine/config.dart';
import '../relation_engine/geometry.dart';
import 'base_models.dart';
import 'contents.dart';
import 'id.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'relations.dart';
import 'styles.dart';
import 'tags.dart';
import 'types.dart';
part 'patches.freezed.dart';

@freezed
sealed class EntityPatch with _$EntityPatch {
  const EntityPatch._();

  const factory EntityPatch.node(List<NodePatch> field0) = EntityPatch_Node;
  const factory EntityPatch.relation(List<RelationPatch> field0) =
      EntityPatch_Relation;
  const factory EntityPatch.createNode(Nodes field0, List<IRelation> field1) =
      EntityPatch_CreateNode;
  const factory EntityPatch.deleteNode(Nodes field0, List<IRelation> field1) =
      EntityPatch_DeleteNode;
  const factory EntityPatch.createRelation(IRelation field0) =
      EntityPatch_CreateRelation;
  const factory EntityPatch.deleteRelation(IRelation field0) =
      EntityPatch_DeleteRelation;
}

/// Atomic composite mutation set representing forward or inverse cascade deltas
class GraphDelta {
  /// Patch existing nodes (undo/redo cascades)
  final List<(TypedRecordId, List<NodePatch>)> nodeUpserts;

  /// Create brand-new nodes (template instantiation)
  final List<Nodes> nodeCreations;
  final List<TypedRecordId> nodeDeletions;

  /// Patch existing relations
  final List<(TypedRecordId, List<RelationPatch>)> relationUpserts;

  /// Create brand-new relations
  final List<IRelation> relationCreations;
  final List<TypedRecordId> relationDeletions;

  const GraphDelta({
    required this.nodeUpserts,
    required this.nodeCreations,
    required this.nodeDeletions,
    required this.relationUpserts,
    required this.relationCreations,
    required this.relationDeletions,
  });

  @override
  int get hashCode =>
      nodeUpserts.hashCode ^
      nodeCreations.hashCode ^
      nodeDeletions.hashCode ^
      relationUpserts.hashCode ^
      relationCreations.hashCode ^
      relationDeletions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphDelta &&
          runtimeType == other.runtimeType &&
          nodeUpserts == other.nodeUpserts &&
          nodeCreations == other.nodeCreations &&
          nodeDeletions == other.nodeDeletions &&
          relationUpserts == other.relationUpserts &&
          relationCreations == other.relationCreations &&
          relationDeletions == other.relationDeletions;
}

@freezed
sealed class NodePatch with _$NodePatch {
  const NodePatch._();

  const factory NodePatch.position(Coordinates field0) = NodePatch_Position;
  const factory NodePatch.size(Size field0) = NodePatch_Size;
  const factory NodePatch.content(Content field0) = NodePatch_Content;
  const factory NodePatch.isExpanded(bool field0) = NodePatch_IsExpanded;
  const factory NodePatch.style([NodeStyle? field0]) = NodePatch_Style;
  const factory NodePatch.tagOp(TagOperation field0) = NodePatch_TagOp;
  const factory NodePatch.significance(int field0) = NodePatch_Significance;
  const factory NodePatch.taskState(TaskState field0) = NodePatch_TaskState;
  const factory NodePatch.shapeType(ShapeType field0) = NodePatch_ShapeType;
  const factory NodePatch.brushType(BrushType field0) = NodePatch_BrushType;
  const factory NodePatch.mediaType(MediaType field0) = NodePatch_MediaType;
  const factory NodePatch.sourceUrl([String? field0]) = NodePatch_SourceUrl;
  const factory NodePatch.title(String field0) = NodePatch_Title;
  const factory NodePatch.verb(String field0) = NodePatch_Verb;
}

@freezed
sealed class RelationPatch with _$RelationPatch {
  const RelationPatch._();

  const factory RelationPatch.verb(String field0) = RelationPatch_Verb;
  const factory RelationPatch.endpoints(
    TypedRecordId field0,
    TypedRecordId field1,
  ) = RelationPatch_Endpoints;
  const factory RelationPatch.style([RelationStyle? field0]) =
      RelationPatch_Style;
  const factory RelationPatch.layout([RelationLayout? field0]) =
      RelationPatch_Layout;
  const factory RelationPatch.directionless(bool field0) =
      RelationPatch_Directionless;
  const factory RelationPatch.routingMode(RoutingMode field0) =
      RelationPatch_RoutingMode;
  const factory RelationPatch.portSides([PortSide? field0, PortSide? field1]) =
      RelationPatch_PortSides;
}

class SymmetricEntityPatch {
  final TypedRecordId id;
  final EntityPatch forward;
  final EntityPatch reverse;

  const SymmetricEntityPatch({
    required this.id,
    required this.forward,
    required this.reverse,
  });

  @override
  int get hashCode => id.hashCode ^ forward.hashCode ^ reverse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SymmetricEntityPatch &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          forward == other.forward &&
          reverse == other.reverse;
}

@freezed
sealed class TagOperation with _$TagOperation {
  const TagOperation._();

  const factory TagOperation.add(TypedRecordId field0) = TagOperation_Add;
  const factory TagOperation.remove(TypedRecordId field0) = TagOperation_Remove;
}
