// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class IRelation {
  final String? id;
  final String? inId;
  final String? outId;
  final String verb;
  final String? visualFormatting;
  final bool directionless;
  final int layer;

  const IRelation({
    this.id,
    this.inId,
    this.outId,
    required this.verb,
    this.visualFormatting,
    required this.directionless,
    required this.layer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      inId.hashCode ^
      outId.hashCode ^
      verb.hashCode ^
      visualFormatting.hashCode ^
      directionless.hashCode ^
      layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IRelation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          inId == other.inId &&
          outId == other.outId &&
          verb == other.verb &&
          visualFormatting == other.visualFormatting &&
          directionless == other.directionless &&
          layer == other.layer;
}

class RelationInput {
  final String from;
  final String to;
  final IRelation props;

  const RelationInput({
    required this.from,
    required this.to,
    required this.props,
  });

  @override
  int get hashCode => from.hashCode ^ to.hashCode ^ props.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationInput &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          props == other.props;
}
