// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'styles.dart';

class IRelationFields {
  final String verb;
  final RelationStyle? style;
  final RelationStyle? resolvedStyle;
  final RelationLayout? layout;
  final RelationLayout? resolvedLayout;
  final RelationDirection direction;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const IRelationFields({
    required this.verb,
    this.style,
    this.resolvedStyle,
    this.layout,
    this.resolvedLayout,
    required this.direction,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      verb.hashCode ^
      style.hashCode ^
      resolvedStyle.hashCode ^
      layout.hashCode ^
      resolvedLayout.hashCode ^
      direction.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IRelationFields &&
          runtimeType == other.runtimeType &&
          verb == other.verb &&
          style == other.style &&
          resolvedStyle == other.resolvedStyle &&
          layout == other.layout &&
          resolvedLayout == other.resolvedLayout &&
          direction == other.direction &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
