// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'styles.dart';

class IRelation {
  final String key;
  final IRelationFields fields;

  const IRelation({required this.key, required this.fields});

  @override
  int get hashCode => key.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IRelation &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          fields == other.fields;
}

class IRelationFields {
  final String in_;
  final String out;
  final String verb;
  final RelationStyle? style;
  final RelationStyle? resolvedStyle;
  final bool directionless;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const IRelationFields({
    required this.in_,
    required this.out,
    required this.verb,
    this.style,
    this.resolvedStyle,
    required this.directionless,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      in_.hashCode ^
      out.hashCode ^
      verb.hashCode ^
      style.hashCode ^
      resolvedStyle.hashCode ^
      directionless.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IRelationFields &&
          runtimeType == other.runtimeType &&
          in_ == other.in_ &&
          out == other.out &&
          verb == other.verb &&
          style == other.style &&
          resolvedStyle == other.resolvedStyle &&
          directionless == other.directionless &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
