// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'routing.freezed.dart';

class Point {
  final double x;
  final double y;

  const Point({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

@freezed
sealed class RoutingMode with _$RoutingMode {
  const RoutingMode._();

  const factory RoutingMode.polyline() = RoutingMode_Polyline;
  const factory RoutingMode.bSpline() = RoutingMode_BSpline;
  const factory RoutingMode.orthogonal() = RoutingMode_Orthogonal;
  const factory RoutingMode.octilinear() = RoutingMode_Octilinear;
  const factory RoutingMode.bezier({
    Point? controlPoint1,
    Point? controlPoint2,
  }) = RoutingMode_Bezier;
  const factory RoutingMode.sineWave({
    Point? controlPoint1,
    Point? controlPoint2,
  }) = RoutingMode_SineWave;
}
