// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tags.freezed.dart';

class Tag {
  final String name;
  final int color;

  const Tag({required this.name, required this.color});

  @override
  int get hashCode => name.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          color == other.color;
}

@freezed
sealed class TagEdge with _$TagEdge {
  const TagEdge._();

  const factory TagEdge.hydrated(Tag field0) = TagEdge_Hydrated;
  const factory TagEdge.pointer(RecordStrings field0) = TagEdge_Pointer;
}
