// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'id.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'traits.dart';
part 'tags.freezed.dart';

class Tag {
  final TypedRecordId key;
  final TagFields fields;

  const Tag({required this.key, required this.fields});

  @override
  int get hashCode => key.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          fields == other.fields;
}

@freezed
sealed class TagEdge with _$TagEdge {
  const TagEdge._();

  const factory TagEdge.hydrated(Tag field0) = TagEdge_Hydrated;
  const factory TagEdge.pointer(TypedRecordId field0) = TagEdge_Pointer;
}

class TagFields {
  final String name;
  final int color;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const TagFields({
    required this.name,
    required this.color,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^ color.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagFields &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          color == other.color &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
