// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FontWeight {
  final int field0;

  const FontWeight({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FontWeight &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class ThemeFields {
  final String name;
  final int primaryColor;
  final int secondaryColor;
  final int tertiaryColor;
  final int accentColor;
  final int canvasAccentColor;
  final String fontFamily;
  final double bodyFontSize;
  final FontWeight bodyFontWeight;
  final double borderRadius;
  final double appBarElevation;
  final double appBarTitleFontSize;
  final FontWeight appBarTitleFontWeight;
  final bool useMaterial3;

  const ThemeFields({
    required this.name,
    required this.primaryColor,
    required this.secondaryColor,
    required this.tertiaryColor,
    required this.accentColor,
    required this.canvasAccentColor,
    required this.fontFamily,
    required this.bodyFontSize,
    required this.bodyFontWeight,
    required this.borderRadius,
    required this.appBarElevation,
    required this.appBarTitleFontSize,
    required this.appBarTitleFontWeight,
    required this.useMaterial3,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      primaryColor.hashCode ^
      secondaryColor.hashCode ^
      tertiaryColor.hashCode ^
      accentColor.hashCode ^
      canvasAccentColor.hashCode ^
      fontFamily.hashCode ^
      bodyFontSize.hashCode ^
      bodyFontWeight.hashCode ^
      borderRadius.hashCode ^
      appBarElevation.hashCode ^
      appBarTitleFontSize.hashCode ^
      appBarTitleFontWeight.hashCode ^
      useMaterial3.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemeFields &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          primaryColor == other.primaryColor &&
          secondaryColor == other.secondaryColor &&
          tertiaryColor == other.tertiaryColor &&
          accentColor == other.accentColor &&
          canvasAccentColor == other.canvasAccentColor &&
          fontFamily == other.fontFamily &&
          bodyFontSize == other.bodyFontSize &&
          bodyFontWeight == other.bodyFontWeight &&
          borderRadius == other.borderRadius &&
          appBarElevation == other.appBarElevation &&
          appBarTitleFontSize == other.appBarTitleFontSize &&
          appBarTitleFontWeight == other.appBarTitleFontWeight &&
          useMaterial3 == other.useMaterial3;
}
