// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'contents.dart';
import 'id.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'relations.dart';
import 'styles.dart';
import 'tags.dart';
import 'theme.dart';
part 'types.freezed.dart';

class CommentNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String text;
  final Size size;

  const CommentNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.text,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      text.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          text == other.text &&
          size == other.size;
}

class DrawingNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final List<String> paths;
  final BrushType brushType;
  final double brushThickness;
  final String brushColor;
  final Size size;
  final bool locked;

  const DrawingNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.paths,
    required this.brushType,
    required this.brushThickness,
    required this.brushColor,
    required this.size,
    required this.locked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      paths.hashCode ^
      brushType.hashCode ^
      brushThickness.hashCode ^
      brushColor.hashCode ^
      size.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawingNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          paths == other.paths &&
          brushType == other.brushType &&
          brushThickness == other.brushThickness &&
          brushColor == other.brushColor &&
          size == other.size &&
          locked == other.locked;
}

class FrameNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String title;
  final NodeStyle? style;
  final Size size;

  const FrameNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.title,
    this.style,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      title.hashCode ^
      style.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          title == other.title &&
          style == other.style &&
          size == other.size;
}

class INode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final Content content;
  final NodeStyle? style;
  final NodeStyle? resolvedStyle;
  final NodeLayout? layout;
  final NodeLayout? resolvedLayout;
  final Size size;
  final int lineCount;
  final bool expandable;
  final bool isExpanded;
  final bool locked;
  final List<TagEdge> tags;
  final List<String> aliases;
  final List<Comment> comments;
  final String? attachment;
  final int significance;

  const INode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.content,
    this.style,
    this.resolvedStyle,
    this.layout,
    this.resolvedLayout,
    required this.size,
    required this.lineCount,
    required this.expandable,
    required this.isExpanded,
    required this.locked,
    required this.tags,
    required this.aliases,
    required this.comments,
    this.attachment,
    required this.significance,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      content.hashCode ^
      style.hashCode ^
      resolvedStyle.hashCode ^
      layout.hashCode ^
      resolvedLayout.hashCode ^
      size.hashCode ^
      lineCount.hashCode ^
      expandable.hashCode ^
      isExpanded.hashCode ^
      locked.hashCode ^
      tags.hashCode ^
      aliases.hashCode ^
      comments.hashCode ^
      attachment.hashCode ^
      significance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is INode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          content == other.content &&
          style == other.style &&
          resolvedStyle == other.resolvedStyle &&
          layout == other.layout &&
          resolvedLayout == other.resolvedLayout &&
          size == other.size &&
          lineCount == other.lineCount &&
          expandable == other.expandable &&
          isExpanded == other.isExpanded &&
          locked == other.locked &&
          tags == other.tags &&
          aliases == other.aliases &&
          comments == other.comments &&
          attachment == other.attachment &&
          significance == other.significance;
}

class IRelation {
  final TypedRecordId key;
  final TypedRecordId in_;
  final TypedRecordId out;
  final IRelationFields fields;

  const IRelation({
    required this.key,
    required this.in_,
    required this.out,
    required this.fields,
  });

  @override
  int get hashCode =>
      key.hashCode ^ in_.hashCode ^ out.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IRelation &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          in_ == other.in_ &&
          out == other.out &&
          fields == other.fields;
}

class InterNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String? style;
  final String verb;
  final String? behavioralFeatures;

  const InterNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    this.style,
    required this.verb,
    this.behavioralFeatures,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      style.hashCode ^
      verb.hashCode ^
      behavioralFeatures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InterNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          style == other.style &&
          verb == other.verb &&
          behavioralFeatures == other.behavioralFeatures;
}

class MapData {
  final String mapName;
  final ViewportState viewportState;
  final String? activeThemeId;
  final DisplayMode displayMode;
  final BoundingBox? optArea;

  const MapData({
    required this.mapName,
    required this.viewportState,
    this.activeThemeId,
    required this.displayMode,
    this.optArea,
  });

  @override
  int get hashCode =>
      mapName.hashCode ^
      viewportState.hashCode ^
      activeThemeId.hashCode ^
      displayMode.hashCode ^
      optArea.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapData &&
          runtimeType == other.runtimeType &&
          mapName == other.mapName &&
          viewportState == other.viewportState &&
          activeThemeId == other.activeThemeId &&
          displayMode == other.displayMode &&
          optArea == other.optArea;
}

class MapTheme {
  final TypedRecordId key;
  final ThemeFields fields;

  const MapTheme({required this.key, required this.fields});

  @override
  int get hashCode => key.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapTheme &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          fields == other.fields;
}

class MediaNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String sourceUrl;
  final MediaType mediaType;
  final Size size;

  const MediaNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.sourceUrl,
    required this.mediaType,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sourceUrl.hashCode ^
      mediaType.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sourceUrl == other.sourceUrl &&
          mediaType == other.mediaType &&
          size == other.size;
}

@freezed
sealed class Nodes with _$Nodes {
  const Nodes._();

  const factory Nodes.iNode(INode field0) = Nodes_INode;
  const factory Nodes.taskNode(TaskNode field0) = Nodes_TaskNode;
  const factory Nodes.interNode(InterNode field0) = Nodes_InterNode;
  const factory Nodes.commentNode(CommentNode field0) = Nodes_CommentNode;
  const factory Nodes.drawingNode(DrawingNode field0) = Nodes_DrawingNode;
  const factory Nodes.shapeNode(ShapeNode field0) = Nodes_ShapeNode;
  const factory Nodes.frameNode(FrameNode field0) = Nodes_FrameNode;
  const factory Nodes.mediaNode(MediaNode field0) = Nodes_MediaNode;
}

class ShapeNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final ShapeType shapeType;
  final NodeStyle? style;
  final Size size;

  const ShapeNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.shapeType,
    this.style,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      shapeType.hashCode ^
      style.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          shapeType == other.shapeType &&
          style == other.style &&
          size == other.size;
}

enum TableKind {
  iNode,
  taskNode,
  interNode,
  commentNode,
  drawingNode,
  shapeNode,
  frameNode,
  mediaNode,
  iRelation,
  tag,
  mapTheme,
  mapData,
  history,
  template,
}

class Tag {
  final TypedRecordId key;
  final TagFields fields;

  const Tag({required this.key, required this.fields});

  @override
  int get hashCode => key.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          fields == other.fields;
}

class TaskNode {
  final TypedRecordId id;
  final Coordinates position;
  final String layer;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final Content content;
  final PlatformInt64? dueDate;
  final TaskState state;
  final Size size;
  final bool expandable;
  final bool isExpanded;
  final NodeStyle? style;
  final NodeStyle? resolvedStyle;
  final NodeLayout? layout;
  final NodeLayout? resolvedLayout;
  final int significance;

  const TaskNode({
    required this.id,
    required this.position,
    required this.layer,
    required this.createdAt,
    required this.updatedAt,
    required this.content,
    this.dueDate,
    required this.state,
    required this.size,
    required this.expandable,
    required this.isExpanded,
    this.style,
    this.resolvedStyle,
    this.layout,
    this.resolvedLayout,
    required this.significance,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      position.hashCode ^
      layer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      content.hashCode ^
      dueDate.hashCode ^
      state.hashCode ^
      size.hashCode ^
      expandable.hashCode ^
      isExpanded.hashCode ^
      style.hashCode ^
      resolvedStyle.hashCode ^
      layout.hashCode ^
      resolvedLayout.hashCode ^
      significance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          position == other.position &&
          layer == other.layer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          content == other.content &&
          dueDate == other.dueDate &&
          state == other.state &&
          size == other.size &&
          expandable == other.expandable &&
          isExpanded == other.isExpanded &&
          style == other.style &&
          resolvedStyle == other.resolvedStyle &&
          layout == other.layout &&
          resolvedLayout == other.resolvedLayout &&
          significance == other.significance;
}

class Template {
  final TypedRecordId key;
  final String name;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final List<Nodes> nodes;
  final List<IRelation> relations;

  const Template({
    required this.key,
    required this.name,
    required this.createdAt,
    required this.updatedAt,
    required this.nodes,
    required this.relations,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      nodes.hashCode ^
      relations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Template &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          nodes == other.nodes &&
          relations == other.relations;
}
