[workspace]
members = [
    "centrode_macros",
    "centrode_domain",
    "centrode_core",
    "centrode_daemon",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
surrealdb = { version = "3.0", features = ["kv-surrealkv", "kv-mem"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
tokio = { version = "1.40", features = ["rt", "macros", "sync", "time"] }
tracing = { version = "0.1", features = ["release_max_level_info"] }
centrode_macros = { path = "centrode_macros" }
centrode_domain = { path = "centrode_domain" }
centrode_daemon = { path = "centrode_daemon" }
