// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/routing.dart';
import '../domain/styles.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BodyConfig {
  final BodyType defaultType;
  final double taperStartWidth;
  final double taperEndWidth;
  final double widthModulateAmplitude;
  final double widthModulateFrequency;

  const BodyConfig({
    required this.defaultType,
    required this.taperStartWidth,
    required this.taperEndWidth,
    required this.widthModulateAmplitude,
    required this.widthModulateFrequency,
  });

  @override
  int get hashCode =>
      defaultType.hashCode ^
      taperStartWidth.hashCode ^
      taperEndWidth.hashCode ^
      widthModulateAmplitude.hashCode ^
      widthModulateFrequency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BodyConfig &&
          runtimeType == other.runtimeType &&
          defaultType == other.defaultType &&
          taperStartWidth == other.taperStartWidth &&
          taperEndWidth == other.taperEndWidth &&
          widthModulateAmplitude == other.widthModulateAmplitude &&
          widthModulateFrequency == other.widthModulateFrequency;
}

enum BodyType { uniform, taper, widthModulate, bundled }

class BundlingConfig {
  final BundlingMode mode;
  final double threshold;

  const BundlingConfig({required this.mode, required this.threshold});

  @override
  int get hashCode => mode.hashCode ^ threshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BundlingConfig &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          threshold == other.threshold;
}

enum BundlingMode { proximity, sharedEndpoint, none }

class EndpointConfig {
  final EndpointShape defaultStartShape;
  final EndpointShape defaultEndShape;
  final double arrowSize;
  final double handleInset;

  const EndpointConfig({
    required this.defaultStartShape,
    required this.defaultEndShape,
    required this.arrowSize,
    required this.handleInset,
  });

  @override
  int get hashCode =>
      defaultStartShape.hashCode ^
      defaultEndShape.hashCode ^
      arrowSize.hashCode ^
      handleInset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EndpointConfig &&
          runtimeType == other.runtimeType &&
          defaultStartShape == other.defaultStartShape &&
          defaultEndShape == other.defaultEndShape &&
          arrowSize == other.arrowSize &&
          handleInset == other.handleInset;
}

class NudgingConfig {
  final bool enabled;
  final double distance;
  final double decayFactor;

  const NudgingConfig({
    required this.enabled,
    required this.distance,
    required this.decayFactor,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ distance.hashCode ^ decayFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NudgingConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          distance == other.distance &&
          decayFactor == other.decayFactor;
}

class RelationEngineConfig {
  final RoutingConfig routing;
  final NudgingConfig nudging;
  final BundlingConfig bundling;
  final bool crossingMinimization;
  final bool incrementalMode;
  final BodyConfig body;
  final EndpointConfig endpoint;
  final bool? applyCompose;

  const RelationEngineConfig({
    required this.routing,
    required this.nudging,
    required this.bundling,
    required this.crossingMinimization,
    required this.incrementalMode,
    required this.body,
    required this.endpoint,
    this.applyCompose,
  });

  @override
  int get hashCode =>
      routing.hashCode ^
      nudging.hashCode ^
      bundling.hashCode ^
      crossingMinimization.hashCode ^
      incrementalMode.hashCode ^
      body.hashCode ^
      endpoint.hashCode ^
      applyCompose.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationEngineConfig &&
          runtimeType == other.runtimeType &&
          routing == other.routing &&
          nudging == other.nudging &&
          bundling == other.bundling &&
          crossingMinimization == other.crossingMinimization &&
          incrementalMode == other.incrementalMode &&
          body == other.body &&
          endpoint == other.endpoint &&
          applyCompose == other.applyCompose;
}

class RoutingConfig {
  final RoutingMode routingMode;
  final double obstacleMargin;
  final double cornerRadius;
  final double projectionFactor;
  final double clampMin;
  final double clampMax;
  final double extensionMin;
  final double extensionScale;

  const RoutingConfig({
    required this.routingMode,
    required this.obstacleMargin,
    required this.cornerRadius,
    required this.projectionFactor,
    required this.clampMin,
    required this.clampMax,
    required this.extensionMin,
    required this.extensionScale,
  });

  @override
  int get hashCode =>
      routingMode.hashCode ^
      obstacleMargin.hashCode ^
      cornerRadius.hashCode ^
      projectionFactor.hashCode ^
      clampMin.hashCode ^
      clampMax.hashCode ^
      extensionMin.hashCode ^
      extensionScale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingConfig &&
          runtimeType == other.runtimeType &&
          routingMode == other.routingMode &&
          obstacleMargin == other.obstacleMargin &&
          cornerRadius == other.cornerRadius &&
          projectionFactor == other.projectionFactor &&
          clampMin == other.clampMin &&
          clampMax == other.clampMax &&
          extensionMin == other.extensionMin &&
          extensionScale == other.extensionScale;
}
