// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ConceptPrediction {
  final String concept;
  final double score;

  const ConceptPrediction({required this.concept, required this.score});

  @override
  int get hashCode => concept.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConceptPrediction &&
          runtimeType == other.runtimeType &&
          concept == other.concept &&
          score == other.score;
}

class ConnectionAuditResult {
  final double score;
  final String status;
  final String message;
  final String? recommendedRelation;

  const ConnectionAuditResult({
    required this.score,
    required this.status,
    required this.message,
    this.recommendedRelation,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      status.hashCode ^
      message.hashCode ^
      recommendedRelation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionAuditResult &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          status == other.status &&
          message == other.message &&
          recommendedRelation == other.recommendedRelation;
}
