// ignore_for_file: avoid_print

import 'dart:io';
import 'package:path/path.dart' as p;

/// Configuration for domain conversion generation between `centrode_core` and `centrode_daemon`.
class ConversionRule {
  final String structName;
  final String module;
  final bool fromDaemon;
  final bool toDaemon;

  const ConversionRule(
    this.structName, {
    required this.module,
    this.fromDaemon = true,
    this.toDaemon = true,
  });
}

/// Registry of boundary domain structs to generate conversions for.
/// To expose or convert a new struct in the future, simply add 1 line here!
const List<ConversionRule> conversionRules = [
  ConversionRule('MapDescriptor', module: 'base_models'),
  ConversionRule('Coordinates', module: 'base_models'),
  ConversionRule('Size', module: 'base_models'),
  ConversionRule('BoundingBox', module: 'base_models'),
  ConversionRule('ViewportState', module: 'base_models'),
];

String stripFrbAnnotations(String content) {
  final lines = content.split('\n');
  final result = <String>[];
  int i = 0;

  while (i < lines.length) {
    final line = lines[i];
    final trimmed = line.trim();

    if (trimmed.startsWith('use flutter_rust_bridge')) {
      i++;
      continue;
    }

    if (trimmed.startsWith('#[frb(')) {
      var frbBlock = line;
      while (!frbBlock.contains(')]') && i + 1 < lines.length) {
        i++;
        frbBlock += lines[i];
      }
      i++;
      continue;
    }

    if (trimmed == '#[frb]') {
      i++;
      continue;
    }

    result.add(line);
    i++;
  }

  return result.join('\n');
}

List<String> extractStructFields(Directory coreDomainDir, String moduleName, String structName) {
  final file = File(p.join(coreDomainDir.path, '$moduleName.rs'));
  if (!file.existsSync()) {
    throw Exception('Module file ${file.path} does not exist for struct $structName');
  }
  final content = file.readAsStringSync();

  final regex = RegExp(
    r'(?:pub\s+)?struct\s+' + RegExp.escape(structName) + r'\s*(?:<[^>]*>)?\s*\{([^}]*)\}',
    multiLine: true,
  );
  final match = regex.firstMatch(content);
  if (match == null) {
    throw Exception('Could not find struct $structName in ${file.path}');
  }

  final body = match.group(1)!;
  final fields = <String>[];
  for (final line in body.split('\n')) {
    final trimmed = line.trim();
    if (trimmed.startsWith('//') || trimmed.startsWith('#[') || trimmed.isEmpty) {
      continue;
    }
    final fieldMatch = RegExp(r'^(?:pub\s+)?([a-zA-Z0-9_]+)\s*:').firstMatch(trimmed);
    if (fieldMatch != null) {
      fields.add(fieldMatch.group(1)!);
    }
  }

  return fields;
}

String generateDaemonConversions(Directory coreDomainDir) {
  final buffer = StringBuffer();
  buffer.writeln('// AUTO-GENERATED by `dart scripts/sync_domain.dart` - DO NOT EDIT MANUALLY.');
  buffer.writeln();

  final modules = conversionRules.map((r) => r.module).toSet();
  for (final mod in modules) {
    buffer.writeln('use crate::domain::$mod::*;');
  }
  buffer.writeln();

  for (final rule in conversionRules) {
    final fields = extractStructFields(coreDomainDir, rule.module, rule.structName);
    final fieldList = fields.map((f) => '            $f: d.$f,').join('\n');

    if (rule.fromDaemon) {
      buffer.writeln('impl From<centrode_daemon::domain::${rule.module}::${rule.structName}> for ${rule.structName} {');
      buffer.writeln('    #[inline]');
      buffer.writeln('    fn from(d: centrode_daemon::domain::${rule.module}::${rule.structName}) -> Self {');
      buffer.writeln('        Self {');
      buffer.writeln(fieldList);
      buffer.writeln('        }');
      buffer.writeln('    }');
      buffer.writeln('}');
      buffer.writeln();
    }

    if (rule.toDaemon) {
      buffer.writeln('impl From<${rule.structName}> for centrode_daemon::domain::${rule.module}::${rule.structName} {');
      buffer.writeln('    #[inline]');
      buffer.writeln('    fn from(d: ${rule.structName}) -> Self {');
      buffer.writeln('        Self {');
      buffer.writeln(fieldList);
      buffer.writeln('        }');
      buffer.writeln('    }');
      buffer.writeln('}');
      buffer.writeln();
    }
  }

  return buffer.toString();
}

void main() {
  final coreDomainDir = Directory('rust/centrode_core/src/domain');
  final coreDomainFile = File('rust/centrode_core/src/domain.rs');
  final daemonDomainDir = Directory('rust/centrode_daemon/src/domain');
  final daemonDomainFile = File('rust/centrode_daemon/src/domain.rs');
  final conversionsFile = File('rust/centrode_core/src/bridge/daemon_conversions.rs');

  if (!coreDomainDir.existsSync()) {
    stderr.writeln('Error: ${coreDomainDir.path} does not exist.');
    exit(1);
  }

  if (daemonDomainDir.existsSync()) {
    daemonDomainDir.deleteSync(recursive: true);
  }
  daemonDomainDir.createSync(recursive: true);

  if (coreDomainFile.existsSync()) {
    final content = coreDomainFile.readAsStringSync();
    final cleaned = stripFrbAnnotations(content);
    daemonDomainFile.writeAsStringSync(cleaned);
    print('Synced domain.rs from centrode_core to centrode_daemon');
  }

  int count = 0;
  for (final entity in coreDomainDir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.rs')) {
      final relativePath = p.relative(entity.path, from: coreDomainDir.path);
      final destPath = p.join(daemonDomainDir.path, relativePath);
      final destFile = File(destPath);
      destFile.parent.createSync(recursive: true);
      final content = entity.readAsStringSync();
      final cleaned = stripFrbAnnotations(content);
      destFile.writeAsStringSync(cleaned);
      count++;
    }
  }

  print('Successfully synced $count domain source files to centrode_daemon/src/domain (FRB annotations stripped).');

  if (!conversionsFile.parent.existsSync()) {
    conversionsFile.parent.createSync(recursive: true);
  }
  conversionsFile.writeAsStringSync(generateDaemonConversions(coreDomainDir));
  print('Successfully generated ${conversionsFile.path}');
}
