// AUTO-GENERATED by `dart scripts/sync_domain.dart` - DO NOT EDIT MANUALLY.

use crate::domain::base_models::*;

impl From<centrode_daemon::domain::base_models::MapDescriptor> for MapDescriptor {
    #[inline]
    fn from(d: centrode_daemon::domain::base_models::MapDescriptor) -> Self {
        Self {
            id: d.id,
            name: d.name,
            storage_path: d.storage_path,
            created_at_ms: d.created_at_ms,
            modified_at_ms: d.modified_at_ms,
            accessed_at_ms: d.accessed_at_ms,
        }
    }
}

impl From<MapDescriptor> for centrode_daemon::domain::base_models::MapDescriptor {
    #[inline]
    fn from(d: MapDescriptor) -> Self {
        Self {
            id: d.id,
            name: d.name,
            storage_path: d.storage_path,
            created_at_ms: d.created_at_ms,
            modified_at_ms: d.modified_at_ms,
            accessed_at_ms: d.accessed_at_ms,
        }
    }
}

impl From<centrode_daemon::domain::base_models::Coordinates> for Coordinates {
    #[inline]
    fn from(d: centrode_daemon::domain::base_models::Coordinates) -> Self {
        Self {
            x: d.x,
            y: d.y,
        }
    }
}

impl From<Coordinates> for centrode_daemon::domain::base_models::Coordinates {
    #[inline]
    fn from(d: Coordinates) -> Self {
        Self {
            x: d.x,
            y: d.y,
        }
    }
}

impl From<centrode_daemon::domain::base_models::Size> for Size {
    #[inline]
    fn from(d: centrode_daemon::domain::base_models::Size) -> Self {
        Self {
            width: d.width,
            height: d.height,
        }
    }
}

impl From<Size> for centrode_daemon::domain::base_models::Size {
    #[inline]
    fn from(d: Size) -> Self {
        Self {
            width: d.width,
            height: d.height,
        }
    }
}

impl From<centrode_daemon::domain::base_models::BoundingBox> for BoundingBox {
    #[inline]
    fn from(d: centrode_daemon::domain::base_models::BoundingBox) -> Self {
        Self {
            min_x: d.min_x,
            min_y: d.min_y,
            max_x: d.max_x,
            max_y: d.max_y,
        }
    }
}

impl From<BoundingBox> for centrode_daemon::domain::base_models::BoundingBox {
    #[inline]
    fn from(d: BoundingBox) -> Self {
        Self {
            min_x: d.min_x,
            min_y: d.min_y,
            max_x: d.max_x,
            max_y: d.max_y,
        }
    }
}

impl From<centrode_daemon::domain::base_models::ViewportState> for ViewportState {
    #[inline]
    fn from(d: centrode_daemon::domain::base_models::ViewportState) -> Self {
        Self {
            x_offset: d.x_offset,
            y_offset: d.y_offset,
            zoom_level: d.zoom_level,
            active_view: d.active_view,
        }
    }
}

impl From<ViewportState> for centrode_daemon::domain::base_models::ViewportState {
    #[inline]
    fn from(d: ViewportState) -> Self {
        Self {
            x_offset: d.x_offset,
            y_offset: d.y_offset,
            zoom_level: d.zoom_level,
            active_view: d.active_view,
        }
    }
}

