// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/config.dart';
import '../domain/nodes.dart';
import '../domain/relations.dart';
import '../frb_generated.dart';
import '../persistence/repo.dart';
import '../telemetry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GraphEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Initialization endpoint for the telemetry layer.
/// Called by Dart during app startup to initialize the tracing subscriber.
Future<void> setupLogger() => RustLib.instance.api.crateBridgeApiSetupLogger();

/// Stream connection endpoint for FFI.
/// Dart calls this after the DiskWriterIsolate is ready.
/// Flushes the pre-stream buffer and starts streaming logs.
Stream<LogState> createLogStream() =>
    RustLib.instance.api.crateBridgeApiCreateLogStream();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppHandle>>
abstract class AppHandle implements RustOpaqueInterface {
  Repository get repo;

  set repo(Repository repo);

  Future<String> createNode({required NodeInput input});

  Future<String> createRelation({required RelationInput input});

  Future<String> deleteNodeEntry({required String table, required String id});

  Future<String> deleteRelation({required String id});

  Future<(List<NodeOutput>, List<IRelation>, MapConfig?)> getGraphSnapshot();

  Future<NodeOutput?> getNode({required String table, required String id});

  Future<void> loadMapFromFile({
    required String filePath,
    required String attachmentDir,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppHandle> newInstance({required String storagePath}) =>
      RustLib.instance.api.crateBridgeApiAppHandleNew(storagePath: storagePath);

  Future<void> patchNodeProperties({
    required String table,
    required String id,
    required String jsonPatch,
  });

  Future<void> patchRelation({required String id, required String jsonPatch});

  Future<String> rerouteRelation({
    required String id,
    required String newFrom,
    required String newTo,
  });

  Future<void> saveMapToFile({
    required String filePath,
    required String attachmentDir,
  });

  Future<void> startGraphStream();
}
