// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/base_models.dart';
import '../domain/contents.dart';
import '../domain/id.dart';
import '../domain/nodes.dart';
import '../domain/patches.dart';
import '../domain/relations.dart';
import '../domain/snapshot.dart';
import '../domain/styles.dart';
import '../domain/tags.dart';
import '../domain/theme.dart';
import '../domain/types.dart';
import '../frb_generated.dart';
import '../layout_engine/config.dart';
import '../layout_engine/types.dart';
import '../persistence/history.dart';
import '../persistence/repo.dart';
import '../relation_engine/computed.dart';
import '../relation_engine/config.dart';
import '../relation_engine/geometry.dart';
import '../telemetry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'stream.dart';

Future<void> setupLogger() => RustLib.instance.api.crateBridgeApiSetupLogger();

Stream<LogState> createLogStream() =>
    RustLib.instance.api.crateBridgeApiCreateLogStream();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppHandle>>
abstract class AppHandle implements RustOpaqueInterface {
  Future<void> addAnchorSpring({
    required TypedRecordId nodeId,
    required double x,
    required double y,
    required double strength,
  });

  Future<void> applyEntityMutation({required SymmetricEntityPatch mutation});

  Future<GraphDelta?> applyHistoryRecordPatch({
    required HistoryRecord record,
    required bool isForward,
  });

  ArcGraphService get service;

  set service(ArcGraphService service);

  Future<void> broadcastBoundaries();

  Future<void> close();

  Future<(double, double)> computeAutoPlacement({
    required TypedRecordId sourceId,
    required PortSide portSide,
  });

  Future<List<ComputedRelation>> computeRelations({
    required RelationEngineConfig config,
    List<TypedRecordId>? relationIds,
  });

  Future<ComputedRelation> computeSingleRelation({
    required RelationEngineConfig config,
    required TypedRecordId edgeId,
    required TypedRecordId fromNodeId,
    required TypedRecordId toNodeId,
    PortSide? fromSide,
    PortSide? toSide,
    RoutingMode? routingMode,
    double? overrideStartX,
    double? overrideStartY,
    double? overrideEndX,
    double? overrideEndY,
  });

  Stream<GraphEvent> createGraphStream();

  Future<void> createNode({required Nodes input});

  Future<void> createRelation({required IRelation input});

  Future<void> createTag({required Tag tag});

  Future<void> createTheme({required String key, required ThemeFields fields});

  Future<void> deleteNodeEntry({required TypedRecordId id});

  Future<void> deleteRelation({required TypedRecordId id});

  Future<void> deleteTag({required String key});

  Future<void> deleteTemplate({required String key});

  Future<String?> getActiveThemeId();

  Future<List<Tag>> getAllTags();

  Future<List<Template>> getAllTemplates();

  Future<List<MapTheme>> getAllThemes();

  Future<String> getAssetAbsolutePath({
    required String assetDir,
    required String hash,
    required String extension_,
  });

  Future<GraphSnapshot> getGraphSnapshot();

  Future<Nodes?> getNode({required TypedRecordId id});

  Future<BoundingBox?> getOptArea();

  Future<Tag?> getTag({required String key});

  Future<MapTheme?> getTheme({required String key});

  Future<Attachment> ingestAsset({
    required String assetDir,
    required String fileName,
    required List<int> fileBytes,
    required String mimeType,
  });

  Future<void> instantiateTemplate({
    required String key,
    required double targetX,
    required double targetY,
  });

  Future<void> loadMapFromFile({
    required String filePath,
    required String attachmentDir,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppHandle> newInstance({
    required String storagePath,
    required String name,
  }) => RustLib.instance.api.crateBridgeApiAppHandleNew(
    storagePath: storagePath,
    name: name,
  );

  Future<List<Nodes>> querySearch({required String query});

  Future<void> rebuildNodeCache();

  Future<HistoryRecord?> redo();

  Future<int> redoCount();

  Future<void> rerouteRelation({
    required TypedRecordId record,
    required TypedRecordId from,
    required TypedRecordId to,
  });

  Future<void> saveMapToFile({
    required String filePath,
    required String attachmentDir,
  });

  Future<void> saveTemplateFromSelection({
    required String name,
    required List<TypedRecordId> nodeKeys,
    required List<TypedRecordId> relationKeys,
  });

  Future<void> setActiveTheme({required String themeKey});

  Future<void> setActiveThemeId({required String themeId});

  Future<void> setAlignmentConstraint({
    required List<TypedRecordId> nodeIds,
    required Axis axis,
  });

  Future<void> setOptArea({BoundingBox? bounds});

  Future<void> triggerLayoutOptimization({
    required LayoutConfig config,
    required List<LayoutPatch> livePositions,
  });

  Future<HistoryRecord?> undo();

  Future<int> undoCount();

  Future<void> updateNode({required Nodes input});

  Future<void> updateNodeCachePositions({
    required List<(TypedRecordId, double, double, double, double)> positions,
  });

  Future<void> updateRelation({required IRelation input});

  Future<void> updateTag({required Tag tag});

  Future<void> updateTheme({required MapTheme theme});

  Future<void> updateViewportState({required ViewportState state});

  static Future<AppHandle> withRepository({required Repository repo}) =>
      RustLib.instance.api.crateBridgeApiAppHandleWithRepository(repo: repo);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < GraphService >>>
abstract class ArcGraphService implements RustOpaqueInterface {}
