// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/base_models.dart';
import '../domain/contents.dart';
import '../domain/id.dart';
import '../domain/nodes.dart';
import '../domain/patches.dart';
import '../domain/relations.dart';
import '../domain/styles.dart';
import '../domain/tags.dart';
import '../domain/types.dart';
import '../frb_generated.dart';
import '../relation_engine/config.dart';
import '../relation_engine/geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'stream.freezed.dart';

@freezed
sealed class GraphEvent with _$GraphEvent {
  const GraphEvent._();

  /// Fine-grained node patch updates (e.g., single position move)
  const factory GraphEvent.nodeUpdated({
    required TypedRecordId id,
    required List<NodePatch> patches,
  }) = GraphEvent_NodeUpdated;

  /// Fine-grained relation patch updates (e.g., control point re-routing)
  const factory GraphEvent.relationUpdated({
    required TypedRecordId id,
    required List<RelationPatch> patches,
  }) = GraphEvent_RelationUpdated;

  /// Atomic batch update for history undo/redo cascades or template instantiations
  const factory GraphEvent.batchUpdated(GraphDelta field0) =
      GraphEvent_BatchUpdated;

  /// Elastic canvas boundary recalculation
  const factory GraphEvent.boundaryUpdated(BoundingBox field0) =
      GraphEvent_BoundaryUpdated;
}
