import 'dart:convert';
import 'dart:math';
import 'dart:ui'; // For Offset and Color

// [ASSUMPTION]: These are the types generated by Flutter Rust Bridge.
// Adjust the import path to match your actual generated file location.
import 'package:flutter/foundation.dart';
import 'package:mycelium/src/rust/bridge/api.dart';
import 'package:mycelium/src/rust/domain/nodes.dart';
import 'package:mycelium/src/rust/domain/relations.dart';
// Or sometimes: import 'package:mycelium/src/rust/frb_generated.dart';

// -----------------------------------------------------------------------------
// ID Normalization Helper
// -----------------------------------------------------------------------------

/// Strips the SurrealDB 'table:' prefix to ensure stable Map keys.
/// SurrealDB returns IDs as 'table:id' (e.g., 'inode:123'), but createNode
/// returns just the ID ('123'). This normalizes all IDs for O(1) lookups.
String _stripTablePrefix(String? raw) {
  if (raw == null) return "unknown";
  final parts = raw.split(':');
  return parts.length > 1 ? parts.sublist(1).join(':') : raw;
}

// -----------------------------------------------------------------------------
// Spatial Hash Grid for O(1) Lookups
// -----------------------------------------------------------------------------

/// Provides O(1) spatial lookups and updates for viewport culling.
/// Divides the canvas into chunks for efficient spatial queries.
class SpatialHashGrid {
  final double chunkSize;
  final Map<Point<int>, Set<String>> _grid = {};

  SpatialHashGrid({this.chunkSize = 1000.0});

  /// Returns the chunk coordinates for a given position.
  Point<int> getChunk(Offset position) =>
      Point(position.dx ~/ chunkSize, position.dy ~/ chunkSize);

  /// Inserts a node ID at the specified position.
  void insert(String nodeId, Offset position) {
    _grid.putIfAbsent(getChunk(position), () => {}).add(nodeId);
  }

  /// Updates a node's position in the grid.
  /// Only modifies the grid if the node moves to a different chunk.
  void update(String nodeId, Offset oldPos, Offset newPos) {
    final oldChunk = getChunk(oldPos);
    final newChunk = getChunk(newPos);
    if (oldChunk != newChunk) {
      _grid[oldChunk]?.remove(nodeId);
      _grid.putIfAbsent(newChunk, () => {}).add(nodeId);
    }
  }

  /// Removes a node from the grid.
  void remove(String nodeId, Offset position) {
    _grid[getChunk(position)]?.remove(nodeId);
  }

  /// Queries all node IDs within the specified rectangular bounds.
  Set<String> queryRect(Rect bounds) {
    final Set<String> visible = {};
    final int minX = bounds.left ~/ chunkSize;
    final int maxX = bounds.right ~/ chunkSize;
    final int minY = bounds.top ~/ chunkSize;
    final int maxY = bounds.bottom ~/ chunkSize;

    for (int x = minX; x <= maxX; x++) {
      for (int y = minY; y <= maxY; y++) {
        final chunk = _grid[Point(x, y)];
        if (chunk != null) visible.addAll(chunk);
      }
    }
    return visible;
  }

  /// Clears all entries from the grid.
  void clear() {
    _grid.clear();
  }
}

// -----------------------------------------------------------------------------
// Reactive ViewState for Granular Updates
// -----------------------------------------------------------------------------
// NOTE: Canvas Interaction State Machine (FSM) classes have been moved to
// lib/features/graph/state/canvas_interaction_states.dart as part of the
// GoF State Pattern refactoring. This enables polymorphic dispatch and
// eliminates circular dependencies between models and controller logic.

/// Manages reactive spatial state for a node, decoupling high-frequency
/// position updates from the structural graph state.
class NodeViewState {
  final String nodeId;
  final ValueNotifier<Offset> positionNotifier;
  final ValueNotifier<Size> sizeNotifier; // Synchronous mathematical truth

  NodeViewState(UiNode node)
      : nodeId = node.id,
        positionNotifier = ValueNotifier<Offset>(node.position),
        sizeNotifier = ValueNotifier<Size>(node.size); // Synchronous initialization

  /// Returns the bounding rect combining position and size.
  Rect get rect => positionNotifier.value & sizeNotifier.value;

  // updateSize(Size newSize) removed to ensure domain-driven constraints

  /// Updates position by a delta amount during drag operations.
  void updatePosition(Offset delta) {
    positionNotifier.value += delta;
  }

  /// Updates position by a screen delta, accounting for the current zoom scale.
  /// Used during drag operations where the delta is in screen coordinates.
  void updatePositionWithScale(Offset screenDelta, double currentScale) {
    if (currentScale <= 0) return; // Scale constraint safety
    final Offset canvasDelta = screenDelta / currentScale;
    positionNotifier.value += canvasDelta;
  }

  /// Syncs the position back to the underlying UiNode after drag ends.
  void syncToNode(UiNode node) {
    node.position = positionNotifier.value;
  }

  /// Disposes the internal ValueNotifiers.
  void dispose() {
    positionNotifier.dispose();
    sizeNotifier.dispose();
  }
}

enum UiNodeType { info, task, inter }

/// The Base Entity for everything on the Canvas.
/// This acts as the "ViewModel" for your nodes.
abstract class UiNode {
  // Core Identity
  String id; // Mutable because we swap Temp ID -> Real ID
  final UiNodeType type;
  
  // Visual Properties (Cached for performance)
  Offset position;
  Size size;
  Color color;
  
  // Common Data
  String text;
  bool isSelected;

  UiNode({
    required this.id,
    required this.type,
    required this.position,
    this.text = "",
    this.size = const Size(100, 60), // Default size
    this.color = const Color(0xFFFFFFFF),
    this.isSelected = false,
  });

  /// Factory to convert the Raw Rust Enum into a Dart UiNode
  static UiNode fromFFI(NodeOutput ffiNode) {
    if (ffiNode is NodeOutput_Info) {
      return InfoUiNode.fromRust(ffiNode.field0);
    } else if (ffiNode is NodeOutput_Task) {
      return TaskUiNode.fromRust(ffiNode.field0);
    } else if (ffiNode is NodeOutput_Inter) {
      return InterUiNode.fromRust(ffiNode.field0);
    } else {
      throw UnsupportedError('Unknown NodeOutput type');
    }
  }

  /// Helper to parse the 'visual_formatting' JSON string from Rust
  static Map<String, dynamic> _parseFormatting(String? json) {
    if (json == null || json.isEmpty) return {};
    try {
      return jsonDecode(json) as Map<String, dynamic>;
    } catch (e) {
      print("Error parsing visual_formatting: $e");
      return {};
    }
  }

  /// Helper to extract position from the parsed JSON
  static Offset _extractPosition(Map<String, dynamic> map) {
    // Check if layout.graph exists
    if (map['layout'] != null && map['layout']['graph'] != null) {
      final g = map['layout']['graph'];
      return Offset(
        (g['x'] as num?)?.toDouble() ?? 0.0,
        (g['y'] as num?)?.toDouble() ?? 0.0,
      );
    }
    return Offset.zero;
  }

  /// Converts the UI state back to a Rust input object for saving/creation
  NodeInput toInput();
  
  /// Creates a copy of this node with the given fields replaced.
  UiNode copyWith({Offset? position});
}

// -----------------------------------------------------------------------------
// Concrete Implementations
// -----------------------------------------------------------------------------

class InfoUiNode extends UiNode {
  final List<String> tags;
  final bool locked;

  InfoUiNode({
    required super.id,
    required super.position,
    required super.text,
    super.color = const Color(0xFFBBDEFB), // Blue-ish default
    this.tags = const [],
    this.locked = false,
  }) : super(type: UiNodeType.info);

  factory InfoUiNode.fromRust(INode source) {
    final format = UiNode._parseFormatting(source.visualFormatting);
    
    return InfoUiNode(
      id: _stripTablePrefix(source.id), // Strip table prefix for stable Map keys
      position: UiNode._extractPosition(format),
      text: source.text ?? "",
      tags: source.tags,
      locked: source.locked,
    );
  }

  @override
  NodeInput toInput() {
    return NodeInput.info(INode(
      id: id.startsWith("temp_") ? null : id, // Don't send temp IDs to DB
      text: text,
      tags: tags,
      locked: locked,
      visualFormatting: jsonEncode({
        "layout": { "graph": { "x": position.dx, "y": position.dy } }
      }),
      layer: 1, // Default
      aliases: [],
      comments: [],
      attachment: null,
      createdAt: DateTime.now().millisecondsSinceEpoch,
      updatedAt: DateTime.now().millisecondsSinceEpoch,
    ));
  }

  @override
  InfoUiNode copyWith({Offset? position}) {
    return InfoUiNode(
      id: id,
      position: position ?? this.position,
      text: text,
      color: color,
      tags: tags,
      locked: locked,
    );
  }
}

class TaskUiNode extends UiNode {
  String state; // TODO: Make this an Enum (Todo, Done)
  DateTime? dueDate;

  TaskUiNode({
    required super.id,
    required super.position,
    required super.text,
    super.color = const Color(0xFFC8E6C9), // Green-ish default
    required this.state,
    this.dueDate,
  }) : super(type: UiNodeType.task);

  factory TaskUiNode.fromRust(TaskNode source) {
    final format = UiNode._parseFormatting(source.visualFormatting);
    
    return TaskUiNode(
      id: _stripTablePrefix(source.id), // Strip table prefix for stable Map keys
      position: UiNode._extractPosition(format),
      text: source.text ?? "",
      state: source.state,
      dueDate: source.dueDate != null 
          ? DateTime.fromMillisecondsSinceEpoch(source.dueDate!) 
          : null,
    );
  }

  @override
  NodeInput toInput() {
    return NodeInput.task(TaskNode(
      id: id.startsWith("temp_") ? null : id,
      text: text,
      state: state,
      dueDate: dueDate?.millisecondsSinceEpoch,
      visualFormatting: jsonEncode({
        "layout": { "graph": { "x": position.dx, "y": position.dy } }
      }),
      createdAt: DateTime.now().millisecondsSinceEpoch,
      updatedAt: DateTime.now().millisecondsSinceEpoch,
    ));
  }

  @override
  TaskUiNode copyWith({Offset? position}) {
    return TaskUiNode(
      id: id,
      position: position ?? this.position,
      text: text,
      color: color,
      state: state,
      dueDate: dueDate,
    );
  }
}

class InterUiNode extends UiNode {
  String verb;
  
  InterUiNode({
    required super.id,
    required super.position,
    super.text = "", // Inters use 'verb' primarily
    super.color = const Color(0xFFFFF9C4), // Yellow-ish
    required this.verb,
  }) : super(type: UiNodeType.inter);

  factory InterUiNode.fromRust(InterNode source) {
     final format = UiNode._parseFormatting(source.visualFormatting);

     return InterUiNode(
       id: _stripTablePrefix(source.id), // Strip table prefix for stable Map keys
       position: UiNode._extractPosition(format),
       verb: source.verb,
       text: source.verb, // Bind text to verb for display simplicity
     );
  }

  @override
  NodeInput toInput() {
    return NodeInput.inter(InterNode(
      id: id.startsWith("temp_") ? null : id,
      verb: verb,
      behavioralFeatures: null,
      visualFormatting: jsonEncode({
        "layout": { "graph": { "x": position.dx, "y": position.dy } }
      }),
      createdAt: DateTime.now().millisecondsSinceEpoch,
      updatedAt: DateTime.now().millisecondsSinceEpoch,
    ));
  }

  @override
  InterUiNode copyWith({Offset? position}) {
    return InterUiNode(
      id: id,
      position: position ?? this.position,
      text: text,
      color: color,
      verb: verb,
    );
  }
}

class UiRelation {
  String id;
  final String fromNodeId;
  final String toNodeId;
  final String label; // "verb"
  final Color color;

  UiRelation({
    required this.id,
    required this.fromNodeId,
    required this.toNodeId,
    this.label = "",
    this.color = const Color(0xFFAAAAAA),
  });

  factory UiRelation.fromFFI(IRelation source) {
    // Map the Rust 'in' and 'out' fields to fromNodeId and toNodeId
    // Strip table prefixes for stable Map key lookups
    return UiRelation(
      id: _stripTablePrefix(source.id), 
      fromNodeId: _stripTablePrefix(source.inId), // Binds the Rust 'in' field
      toNodeId: _stripTablePrefix(source.outId),  // Binds the Rust 'out' field
      label: source.verb,
    );
  }

  RelationInput toInput() {
    return RelationInput(
        from: fromNodeId,
        to: toNodeId,
        props: IRelation(
            id: id.startsWith("temp_") ? null : null, // ID handled by DB
            inId: null,  // Not used for input
            outId: null, // Not used for input
            verb: label,
            visualFormatting: null,
            directionless: false,
            layer: 0
        )
    );
  }

  /// Creates a copy of this relation with optionally updated fields.
  /// Used for optimistic label updates during inline editing.
  UiRelation copyWith({String? id, String? label, Color? color}) {
    return UiRelation(
      id: id ?? this.id,
      fromNodeId: fromNodeId,
      toNodeId: toNodeId,
      label: label ?? this.label,
      color: color ?? this.color,
    );
  }
}

// -----------------------------------------------------------------------------
// Command Pattern for State Mutations with Write-Behind Debouncing
// -----------------------------------------------------------------------------

/// Abstract base class for all graph mutation commands.
/// Implements the Command Pattern for undoable operations with FFI sync.
abstract class GraphCommand {
  /// The ID of the entity being modified.
  String get targetId;
  
  /// Executes the command (typically an FFI call).
  Future<void> execute();
  
  /// Rolls back local state on FFI failure.
  void undo();
}

/// Command for moving a node position with atomic rollback support.
/// Captures both the new position and the rollback position for error recovery.
class MoveNodeCommand implements GraphCommand {
  @override
  final String targetId;
  final Offset newPosition;
  final Offset rollbackPosition;
  final NodeViewState nodeViewState;
  final SpatialHashGrid spatialGrid;
  final AppHandle api;
  final String tableName;
  
  /// Callback invoked on successful FFI sync to update canonical DB baseline.
  final VoidCallback onSuccess;
  
  /// Callback invoked on rollback to synchronize the domain model.
  final void Function(Offset) onUndo;

  MoveNodeCommand({
    required this.targetId,
    required this.newPosition,
    required this.rollbackPosition,
    required this.nodeViewState,
    required this.spatialGrid,
    required this.api,
    required this.tableName,
    required this.onSuccess,
    required this.onUndo,
  });

  @override
  Future<void> execute() async {
    final patchJson = jsonEncode({
      "visual_formatting": jsonEncode({
        "layout": { "graph": { "x": newPosition.dx, "y": newPosition.dy } }
      })
    });
    await api.patchNodeProperties(table: tableName, id: targetId, jsonPatch: patchJson);
  }

  @override
  void undo() {
    nodeViewState.positionNotifier.value = rollbackPosition;
    spatialGrid.update(targetId, newPosition, rollbackPosition);
    onUndo(rollbackPosition); // Synchronizes the Domain Model
  }
}

/// Command for deleting a node with rollback support.
/// Captures the node data for restoration on FFI failure.
class DeleteNodeCommand implements GraphCommand {
  @override
  final String targetId;
  final AppHandle api;
  final String tableName;
  final UiNode nodeData;
  final void Function(UiNode) onUndo;
  final SpatialHashGrid spatialGrid;

  DeleteNodeCommand({
    required this.targetId,
    required this.api,
    required this.tableName,
    required this.nodeData,
    required this.onUndo,
    required this.spatialGrid,
  });

  @override
  Future<void> execute() async {
    await api.deleteNodeEntry(table: tableName, id: targetId);
  }

  @override
  void undo() {
    onUndo(nodeData);
    spatialGrid.insert(targetId, nodeData.position);
  }
}

/// Command for updating text content with debounced write-behind sync.
/// Handles both node text and relation labels with appropriate field mapping.
class UpdateTextCommand implements GraphCommand {
  @override
  final String targetId;
  final String tableName;
  final String newText;
  final String oldText;
  final bool isRelation;
  final AppHandle api;
  final VoidCallback onUndo;

  UpdateTextCommand({
    required this.targetId,
    required this.tableName,
    required this.newText,
    required this.oldText,
    required this.isRelation,
    required this.api,
    required this.onUndo,
  });

  @override
  Future<void> execute() async {
    final tName = isRelation ? "relates_to" : tableName;
    final field = (tName == "inter_node" || isRelation) ? "verb" : "text";
    final patchJson = jsonEncode({field: newText});

    if (isRelation) {
      // Defensive Gate: Relations need table prefix since only ID is passed
      final String ffiId = targetId.contains(':') ? targetId : "$tName:$targetId";
      await api.patchRelation(id: ffiId, jsonPatch: patchJson);
    } else {
      // Nodes: Rust combines table + id internally, pass raw ID
      await api.patchNodeProperties(table: tName, id: targetId, jsonPatch: patchJson);
    }
  }

  @override
  void undo() {
    onUndo();
  }
}