import 'dart:convert';
import 'dart:ui'; // For Offset and Color

// [ASSUMPTION]: These are the types generated by Flutter Rust Bridge.
// Adjust the import path to match your actual generated file location.
import 'package:mycelium/src/rust/bridge/api.dart';
import 'package:mycelium/src/rust/domain/nodes.dart';
import 'package:mycelium/src/rust/domain/relations.dart';
// Or sometimes: import 'package:mycelium/src/rust/frb_generated.dart';

enum UiNodeType { info, task, inter }

/// The Base Entity for everything on the Canvas.
/// This acts as the "ViewModel" for your nodes.
abstract class UiNode {
  // Core Identity
  String id; // Mutable because we swap Temp ID -> Real ID
  final UiNodeType type;
  
  // Visual Properties (Cached for performance)
  Offset position;
  Size size;
  Color color;
  
  // Common Data
  String text;
  bool isSelected;

  UiNode({
    required this.id,
    required this.type,
    required this.position,
    this.text = "",
    this.size = const Size(100, 60), // Default size
    this.color = const Color(0xFFFFFFFF),
    this.isSelected = false,
  });

  /// Factory to convert the Raw Rust Enum into a Dart UiNode
  static UiNode fromFFI(NodeOutput ffiNode) {
    if (ffiNode is NodeOutput_Info) {
      return InfoUiNode.fromRust(ffiNode.field0);
    } else if (ffiNode is NodeOutput_Task) {
      return TaskUiNode.fromRust(ffiNode.field0);
    } else if (ffiNode is NodeOutput_Inter) {
      return InterUiNode.fromRust(ffiNode.field0);
    } else {
      throw UnsupportedError('Unknown NodeOutput type');
    }
  }

  /// Helper to parse the 'visual_formatting' JSON string from Rust
  static Map<String, dynamic> _parseFormatting(String? json) {
    if (json == null || json.isEmpty) return {};
    try {
      return jsonDecode(json) as Map<String, dynamic>;
    } catch (e) {
      print("Error parsing visual_formatting: $e");
      return {};
    }
  }

  /// Helper to extract position from the parsed JSON
  static Offset _extractPosition(Map<String, dynamic> map) {
    // Check if layout.graph exists
    if (map['layout'] != null && map['layout']['graph'] != null) {
      final g = map['layout']['graph'];
      return Offset(
        (g['x'] as num?)?.toDouble() ?? 0.0,
        (g['y'] as num?)?.toDouble() ?? 0.0,
      );
    }
    return Offset.zero;
  }
  
  /// Helper to extract color (naive implementation for now)
  static Color _extractColor(Map<String, dynamic> map) {
    // In config.rs, color is in overrides.bg_color or theme
    // For now, return a default.
    return const Color(0xFFE0E0E0); 
  }

  /// Converts the UI state back to a Rust input object for saving/creation
  NodeInput toInput();
}

// -----------------------------------------------------------------------------
// Concrete Implementations
// -----------------------------------------------------------------------------

class InfoUiNode extends UiNode {
  final List<String> tags;
  final bool locked;

  InfoUiNode({
    required super.id,
    required super.position,
    required super.text,
    super.color = const Color(0xFFBBDEFB), // Blue-ish default
    this.tags = const [],
    this.locked = false,
  }) : super(type: UiNodeType.info);

  factory InfoUiNode.fromRust(INode source) {
    final format = UiNode._parseFormatting(source.visualFormatting);
    
    return InfoUiNode(
      id: source.id ?? "unknown_id", // Should safeguard against nulls
      position: UiNode._extractPosition(format),
      text: source.text ?? "",
      tags: source.tags,
      locked: source.locked,
    );
  }

  @override
  NodeInput toInput() {
    return NodeInput.info(INode(
      id: id.startsWith("temp_") ? null : id, // Don't send temp IDs to DB
      text: text,
      tags: tags,
      locked: locked,
      visualFormatting: jsonEncode({
        "layout": { "graph": { "x": position.dx, "y": position.dy } }
      }),
      layer: 1, // Default
      aliases: [],
      comments: [],
      attachment: null,
      createdAt: DateTime.now().millisecondsSinceEpoch,
      updatedAt: DateTime.now().millisecondsSinceEpoch,
    ));
  }
}

class TaskUiNode extends UiNode {
  String state; // TODO: Make this an Enum (Todo, Done)
  DateTime? dueDate;

  TaskUiNode({
    required super.id,
    required super.position,
    required super.text,
    super.color = const Color(0xFFC8E6C9), // Green-ish default
    required this.state,
    this.dueDate,
  }) : super(type: UiNodeType.task);

  factory TaskUiNode.fromRust(TaskNode source) {
    final format = UiNode._parseFormatting(source.visualFormatting);
    
    return TaskUiNode(
      id: source.id ?? "unknown_id",
      position: UiNode._extractPosition(format),
      text: source.text ?? "",
      state: source.state,
      dueDate: source.dueDate != null 
          ? DateTime.fromMillisecondsSinceEpoch(source.dueDate!) 
          : null,
    );
  }

  @override
  NodeInput toInput() {
    return NodeInput.task(TaskNode(
      id: id.startsWith("temp_") ? null : id,
      text: text,
      state: state,
      dueDate: dueDate?.millisecondsSinceEpoch,
      visualFormatting: jsonEncode({
        "layout": { "graph": { "x": position.dx, "y": position.dy } }
      }),
      createdAt: DateTime.now().millisecondsSinceEpoch,
      updatedAt: DateTime.now().millisecondsSinceEpoch,
    ));
  }
}

class InterUiNode extends UiNode {
  String verb;
  
  InterUiNode({
    required super.id,
    required super.position,
    super.text = "", // Inters use 'verb' primarily
    super.color = const Color(0xFFFFF9C4), // Yellow-ish
    required this.verb,
  }) : super(type: UiNodeType.inter);

  factory InterUiNode.fromRust(InterNode source) {
     final format = UiNode._parseFormatting(source.visualFormatting);

     return InterUiNode(
       id: source.id ?? "unknown_id",
       position: UiNode._extractPosition(format),
       verb: source.verb,
       text: source.verb, // Bind text to verb for display simplicity
     );
  }

  @override
  NodeInput toInput() {
    return NodeInput.inter(InterNode(
      id: id.startsWith("temp_") ? null : id,
      verb: verb,
      behavioralFeatures: null,
      visualFormatting: jsonEncode({
        "layout": { "graph": { "x": position.dx, "y": position.dy } }
      }),
      createdAt: DateTime.now().millisecondsSinceEpoch,
      updatedAt: DateTime.now().millisecondsSinceEpoch,
    ));
  }
}

class UiRelation {
  String id;
  final String fromNodeId;
  final String toNodeId;
  final String label; // "verb"
  final Color color;

  UiRelation({
    required this.id,
    required this.fromNodeId,
    required this.toNodeId,
    this.label = "",
    this.color = const Color(0xFFAAAAAA),
  });

  factory UiRelation.fromFFI(IRelation source) {
    // Assuming IRelation has from/to fields in the struct
    // Note: Rust 'IRelation' struct in your upload didn't show 'from'/'to' explicitly
    // inside the struct itself (they were in RelationInput).
    // *Check your Rust 'IRelation' definition.* // If 'IRelation' lacks endpoints, we must fetch them from the 'relates_to' table data.
    return UiRelation(
      id: source.id?.toString() ?? "unknown",
      fromNodeId: "TODO_FETCH_FROM_ID", // See note below
      toNodeId: "TODO_FETCH_TO_ID",
      label: source.verb,
    );
  }

  RelationInput toInput() {
    return RelationInput(
        from: fromNodeId,
        to: toNodeId,
        props: IRelation(
            id: id.startsWith("temp_") ? null : null, // ID handled by DB
            verb: label,
            visualFormatting: null,
            directionless: false,
            layer: 0
        )
    );
  }
}